### ISSUE TITLE
UI bug/Duration Slowdown source detected - display of affecting is cut

### ISSUE THREAD

**Issue by arik-dig** [digma-ai/digma-intellij-plugin#1097]
seeing 2 Issues A , B

### Issue A - here's the problematic display

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/6c6d602f-5e9e-4a08-a68d-b249032971e7)

- when resizing seeing 2 types of wrapps

1. one liner 

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/c4fe5010-54a5-4aef-a056-3043fd02ffac)

2. two liner (right part of duration)

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/3e524a65-ca63-4203-90ec-7717978a705e)

### Issue B - tool tip on the **entire** panel

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/c5eab1f7-3b17-4612-b75d-41e193bc7661)

**Comment by shalom938** [comment]
not relevant after switching to the new insights app
