### ISSUE TITLE
Add timer with notification if no insight received

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1114]
After 'Server first connected' event, start a timer.
If more than 30 minutes passed, show a notification with the following text:
'We noticed Digma hasn't received any data yet, do you need help with setup? "
Action should be link to "Troubleshoot"

**Comment by shaykeren** [comment]
* please add an event when the user clicks the troubleshooting link
* [Question] What will happen if IDE is not in focus? will the user get the notification once it gets focused?
