### ISSUE TITLE
Display bug - Duration slowdown source detected insight

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#1119]
see attached video 

this bug might be related to https://github.com/digma-ai/digma-intellij-plugin/issues/1097

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUVCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a3b3d62eefb31c5f9b1e7ab897611dc8d8f68152/slowdown_source_bug.mov)

**Comment by shaykeren** [comment]
moving to react insights view

**Comment by shaykeren** [comment]
moving to react insights view

**Comment by shalom938** [comment]
not relevant after switching to the new insights app
