### ISSUE TITLE
UI Bug/when span name is long - it affects the insight panel too much space for display

### ISSUE THREAD

**Issue by arik-dig** [digma-ai/digma-intellij-plugin#1126]
![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/b4270480-ae58-4ee7-a9c5-2a59b192c9ce)

**Comment by arik-dig** [comment]
@doppleware how should it be fixed? 
I guess need to trim the value, but up until what?

**Comment by arik-dig** [comment]
@doppleware 
maybe we should consider adding icon for copy the complete span name into clipboard
https://www.google.com/search?q=copy+to+clipboard+icon&tbm=isch
![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/9e07e1aa-021d-4fa7-8051-9eec0f7481d5)

**Comment by doppleware** [comment]
1. Trim the first 50 characters
2. The icon is a good idea, I can ask inkode, but also need a tooltip with the full text

**Comment by shaykeren** [comment]
moving to react insights view
