### ISSUE TITLE
Digma works best with IntelliJ 2023.2 - notification

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#1138]
show notification (current area that we are using the backend/plugin update notification) if user using version which is less than 23.2 and os type is mac/linux and IDEA IDE
message: Digma works best with IntelliJ 2023.2 with ‘update’ button
update button action should open the following link: https://www.jetbrains.com/idea/download/
show notification every time plugin is loaded
when user clicks the update button we should hide the notification, until he’ll restart again his IDE

**Comment by shalom938** [comment]
[Screencast from 2023-08-16 16-16-36.webm](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/43a55830-01dc-4bf0-9418-56b5bc8cb64d)
