### ISSUE TITLE
when opening insights close the wizard if its open

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#1175]
if user completed installation but did not finish the wizard , then clicks a recent activity, or first important insights, the wizard will stay on .
need to close the wizard in that case. the wizard will be disposed.

**Comment by shaykeren** [comment]
@shalom938 so in that case the finish button won't be clicked, just make sure that the finish event (if there is one) is not an important activity event for us (ask @doppleware ).

**Comment by shaykeren** [comment]
duplicate issue: https://github.com/digma-ai/digma-intellij-plugin/issues/1177
