### ISSUE TITLE
Support the Tomcat Server plugin 

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1198]
1. Support the Tomcat Server plugin Probably available in IntelliJ Ultimate only
See screenshot: https://drive.google.com/file/d/16gULJqOYnqN5QyarjpPPyqZ0CT-t7LHx/view?usp=sharing
2. Support the Tomcat Gradle plugin

**Comment by shalom938** [comment]
@doppleware @arik-dig @shaykeren 
how urgent is to support also running tomcat with gradle?
there are a few tomcat plugins for gradle
https://plugins.gradle.org/search?term=tomcat

**Comment by shalom938** [comment]
there are also other external plugins for running tomcat in ultimate

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/c3de787d-9a2c-40e3-9f09-dbbd0312cf7b)

**Comment by shalom938** [comment]
and tomcat runner which is only supported in community
![image](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/83ae3f3e-4850-4496-8baf-200a89dac1de)

**Comment by shalom938** [comment]
another thing, for a GWT application there is also a dedicated intellij run configuration

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/3b6f96bb-6b3a-489a-bf22-01a1ac56999b)

**Comment by doppleware** [comment]
We'll need to support these, but for now lets concentrate on what the beta user was using in the screenshot. 
If we need more info lets reach out to them.

**Comment by shalom938** [comment]
How to use tomcat server configuration in intellij ultimate:
prerequisites:  maven, tomcat
I tested with a GWT sample app:
https://github.com/eugenp/tutorials/blob/master/web-modules/google-web-toolkit/README.md
build the app with: 'mvn clean package'

install tomcat somewhere, this sample worked with tomcat 8, couldn't make it work with tomcat 10.

open the sample in idea ultimate, let idea install the GWT plugin.
configure a tomcat run configuration,
![image](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/8415bb6b-62b1-4413-b1b0-dc49cb89c06f)
![image](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/542eeccd-025a-4794-bb9e-ac4a0b1267c2)

configure url and application context as in the screenshot above.
start tomcat
got to 
http://localhost:8080/google_web_toolkit/greet/
click submit and thanks few times
![image](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/a1cffb7e-9613-4ac5-8cd2-ba3ba68b16c4)

you should see insights already.

two ways to change the service name:
in the run configuration add vm option: -Dotel.service.name=myservice
or in startup/connection add env variable: JAVA_OPTS=-Dotel.service.name=myservice_4

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/7354ec94-b17a-4a07-9d04-3e8f844cb303)
![image](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/c328443e-22bc-4ff6-a9ff-8933eed73472)

**Comment by shalom938** [comment]
Ultimate has a GWT plugin, GWT plugin adds a 'GWT configuration'
i still could not find a way to support it, it is not a standard run configuration.
![image](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/29d5eba5-a0d2-4cdf-928b-f3f4e0bf0be3)

**Comment by shalom938** [comment]
intellij community has a GWTP (GTW platform) plugin , but it only adds code assist and does not add the GWT run configuration
