### ISSUE TITLE
Flickering in empty state panel

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1255]
See attached animated gif
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjV5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c93fb65787229dd81da23e0a9880248ea15bc6a3/idea64_x8ayaxfstr%20%281%29.gif)

**Comment by kshmidt-digma** [comment]
Duplicate of https://github.com/digma-ai/digma-ui/issues/211
