### ISSUE TITLE
Add required system properties to prevent Mockito from failing

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1267]
Currently if you don't include the following it may fail to run tests with Mockito:

```
tasks.test {
    systemProperties(Pair("otel.javaagent.experimental.field-injection.enabled", "false"))
}
```
if you're using Gradle groovy (build.gradle) so please add the following:
```
test {
  systemProperty 'otel.javaagent.experimental.field-injection.enabled', 'false'
}
```
The tests with crash.
We should add these system properties if the user is using Mockito and enables observability via Digma**

- relates to workaround provided by OTEL people:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8862#issuecomment-1619722050

**Comment by arik-dig** [comment]
### Approach A

1. going to affect the runconfig runtime only
2. need to check if its a test goal/task
3. need to check if deps of module has Mockito
4. if both 3 and 2 are true, going to modify the system properties during runtime

**Comment by doppleware** [comment]
sounds good, maybe we can just add the property though? Don't think it will do any harm
