### ISSUE TITLE
Add analytics to CI environment

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1305]
We need events for:
1. The user clicked on new environments 
2. The user selected an environment type (with property of CI/Prod or Digma Env)
3. The user clicked the 'Test' button with property of the result and the value he used
4. The user clicked the 'Finish' button with a property of the result (success/fail + error message)
5. Recent activity first data received for an environment (with property of environment type - CI/Prod or Digma Env). For this we can just send an event if we moved from 0 traces to 1 or up.

**Comment by kshmidt-digma** [comment]
The first 4 cases will be covered in the scope of https://github.com/digma-ai/digma-ui/issues/216
