### ISSUE TITLE
first important insight is shown twice

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#1310]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGpCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b3a979f2a1582f1bd63a102691ea90ad61f451fc/Screenshot%20from%202023-09-21%2011-17-44.png)

**Comment by borisermakof** [comment]
I added 2 envs, and for each env it showed me first insight, when im trying to click `ShowInsights`, it navigates to one ENV, but when i c
<img width="437" alt="Screenshot 2023-09-21 at 12 43 23" src="https://github.com/digma-ai/digma-intellij-plugin/assets/8687862/0dbd637d-2e6b-4907-9449-735ba65e8423">
lick on another `ShowInsight`, its navigates, but for the same env
