### ISSUE TITLE
When I put the IDE into background, after some minutes it pops back up out of nowhere.

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#1360]
https://youtrack.jetbrains.com/issue/IDEA-333567/IntelliJ-pops-to-front-in-seemingly-random-fashion
check the  Digma channel for more details

**Comment by kshmidt-digma** [comment]
Attaching logs for this case (encountered two times):
[idea.log](https://github.com/digma-ai/digma-intellij-plugin/files/13043429/idea.log)
[idea_2.log](https://github.com/digma-ai/digma-intellij-plugin/files/13043428/idea_2.log)

Environment: Meloona

IDE: IntelliJ IDEA 2023.2.3 (Community Edition)
Build #IC-232.10072.27, built on October 11, 2023
Runtime version: 17.0.8.1+7-b1000.32 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.intellij.remoteControl (232.8660.88)
    org.digma.intellij (2.0.187+232)

Kotlin: 232-1.9.0-IJ10072.27

**Comment by kshmidt-digma** [comment]
I'm not sure if that is related, but after popping up, I've noticed that Assets tab content is not responsive
https://github.com/digma-ai/digma-intellij-plugin/assets/119138536/3949a908-2b38-406f-9873-ae8be0e2ea83

**Comment by kshmidt-digma** [comment]
It happened one more time to me.
[idea_3.log](https://github.com/digma-ai/digma-intellij-plugin/files/13112545/idea_3.log)

All these 3 times, my IDE has a running application, and the Assets tab is not responsive as well
<img width="521" alt="image" src="https://github.com/digma-ai/digma-intellij-plugin/assets/119138536/9b887a82-e00b-43d6-91bd-6215ac04a4c4">

**Comment by kshmidt-digma** [comment]
...and again, Assets tab is responsible this time
<img width="1276" alt="image" src="https://github.com/digma-ai/digma-intellij-plugin/assets/119138536/79f66187-b7c6-4c17-8246-a80bdede6488">
[idea_4.log](https://github.com/digma-ai/digma-intellij-plugin/files/13163325/idea_4.log)
