### ISSUE TITLE
Add analytics for auto engine stop/remove events via the UI

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1365]
We need to know if the user removed Digma or stopped it via the Engineering

**Comment by shalom938** [comment]
@doppleware 
we have this event, is this what you mean?
"installation wizard engine action button clicked"


![image](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/e7d6c138-b0d0-4ffe-8140-a81228b29020)

**Comment by doppleware** [comment]
yes this is okay, thanks!
