### ISSUE TITLE
Add retention analytics

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1366]
1. Save first activated (assets-first-received) date in posthog (currently its a boolean)
2. Save 'lastUserAction' property, also date time, that gets updated every time the 'user-action' event is activated

**Comment by shalom938** [comment]
@doppleware 
can you please clarify?

> Save first activated (assets-first-received) date in posthog (currently its a boolean)

do you want the date of firstTimeAssetsReceived?

> Save 'lastUserAction' property, also date time, that gets updated every time the 'user-action' event is activated
don't understand where to add the property

**Comment by doppleware** [comment]
Hi! I need two new properties for each person, both datetime.  Not event property, person property.
1. The first time (and probably only) that the event  asset-first-received happened
2. lastUserAction - the last time a user-action event was triggered.
