### ISSUE TITLE
view/recent files - digma icon too big  IDEA 2023.3 Beta

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#1439]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHdJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca82d843954b6abd669b3fa61959e120d3435088/Screenshot%202023-11-26%20at%2010.53.36%20AM.png)

**Comment by shalom938** [comment]
needs a 13x13 icon ,the current icon is too big

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/ad05a954-b26e-4200-85f3-82425d446236)
