### ISSUE TITLE
Handle change of digma-analytics backend in the plugin

### ISSUE THREAD

**Issue by ohrebeniuk** [digma-ai/digma-intellij-plugin#1449]
The following situation is possible when changing the digma backend. The plugin doesn't refresh services if another backend is configured to a different project with another services.
MELOONA env has to show their services.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1FlQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5892a2e23566086b1db2706fd7b88844a2462dd5/image.png)

**Comment by kshmidt-digma** [comment]
Closed in https://github.com/digma-ai/digma-intellij-plugin/pull/1743
