### ISSUE TITLE
Environment not set when using Micrometer Tracing

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1456]
STR:
Create an environment in DIgma UI. Click on "Add to the Active Run Config"
Traces will appear as "UNSET ENV"

Expected behavior:
Trace to appear under the requested environment

**Comment by arik-dig** [comment]
the UI looks like this:

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/049d0e6f-3f10-4939-a4aa-058d6f2869c9)

meaning it contains the standard OTEL_RESOURCE_ATTRIBUTES however for SpringBoot Micrometer need to have something different :

`MANAGEMENT_OPENTELEMETRY_RESOURCE-ATTRIBUTES_digma_environment=MY_ENV`

@doppleware  do we want to modify the UI as well (conditionally if spring boot is configured)?

**Comment by arik-dig** [comment]
@kshmidt-digma , @doppleware can you open a ticket for the UI?

**Comment by kshmidt-digma** [comment]
UI Part is covered in https://github.com/digma-ai/digma-intellij-plugin/issues/1456

@doppleware please review
