### ISSUE TITLE
Inject commit hash into env variable when running/debugging in IDE

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1468]
Use our convention for commit info (also used in .net)
When running inject an env variable into the run config for the resource attribute with the commit hash using the IDE source control integration to get the data

resource attribute name: scm.commit.id

**Comment by shalom938** [comment]
There may be multiple vcs roots. decided with Shay that in this case we will not add the commit hash to the run config and send posthog event.

**Comment by doppleware** [comment]
Multiple roots for the module ?
