### ISSUE TITLE
Kotlin - Ktor support

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#1473]

**Comment by shalom938** [comment]
when the cursor in on ktor endpoint the endpoint insights are shown
![image](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/6cdcd203-c94a-4b38-9f7f-2aa7e3f10130)

**Comment by shalom938** [comment]
when the cursor is not in endpoint scope all the insights for all endpoints are shown.
code lens for all endpoints are shown on the method declaration.

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/42b39bf0-7f5c-4f3e-bf64-bfaa5527f4ac)

**Comment by shalom938** [comment]
ktor endpoint discovery is implemented partially for RoutingBuilderKt.
need to implement for RegexRouting (get(Regex("/(?<name>.+)/hello")){})   and resources ( as get<MyResource>{})

**Comment by doppleware** [comment]
okay for now
