### ISSUE TITLE
Issues with Jetty + activeweb + guice

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1483]
It seems like for proxies guice is injecting some strings into the code.namespace:

the real code is com.moduleA.moduleB.server.v1.controller.admin.Controller.functionA but this is what we see in the attributes: 

code.function=functionA
code.namespace=
com.moduleA.moduleB.server.v1.controller.admin.Controller$$EnhancerByGuice$$df28b4be

This entire section: $$EnhancerByGuice$$df28b4be  needs to be ignored 

In addition, it looks like there is no fallback to client side discovery, this is how the controller is defined:

```
@Path("/v1/admin/path")
class Controller

@GET 
@Produces({"application/json;qs=1","application/x-protostuff","application/x-protobuf","application/xml;qs=.5"})
functionA
```

**Comment by arik-dig** [comment]
@doppleware what do you mean when you say "it looks like there is no fallback to client side discovery"

assuming Is it a JAX-RS annotations, so you would expect that method `functionA` would be recognized as endpoint "/v1/admin/path" - simply as defined in the controller?

**Comment by doppleware** [comment]
So the situation is that there is both method code object id (which is wrong because of the GUICE appended string)
and the route / span code object id.

If want to know whether its by design that if both exist we go by the method code object id. If so it means that we don't use the client side discovery based on route in that scenario. For the customer it means that nothing is working.

**Comment by arik-dig** [comment]
@doppleware this issue is left open because of the client side discovery of endpoints.
do you happen to figure out what are the annotations FQNs (of @path and @get)?
since its not JAX-RS standard.

**Comment by doppleware** [comment]
dependency jsr311-api:1.1.1

**Comment by arik-dig** [comment]
OK JSR 311 is indeeded JAX-RS annotations.
so package name is `javax.ws.rs` and FQN for example is `javax.ws.rs.GET` so its supposed to be suppported

**Comment by arik-dig** [comment]
@GET
