### ISSUE TITLE
New API for code lens

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#1552]
user the latest API, should support backward compatibility.
in case this API return 404 (new plugin version with old backend version)
in such case should not render code lens 
- make sure that the docker-compose file is updated with the backend version with the new API
- version file should be changed when plugin published (backend+plugin versions)

**Comment by shalom938** [comment]
related to code vision see this
https://youtrack.jetbrains.com/issue/IDEA-333164
