### ISSUE TITLE
A micronaut module was still instrumented

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1580]
This was the run config 
<img width="894" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnkzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50e652031874e18fc1c49ef00a832fa6e002db83/image.png" alt="image.png" />

We implemented a feature that the agent won't be used for Micronaut.
The customer uses Micronaut and got the latest plugin but the agent was still used causing issues.
Required behavior: Dont use agent if module is Micronaut

**Comment by arik-dig** [comment]
it works for Kotlin as well.
look like timing issue - it takes us some time to figure out which deps does a module have, and the default is:
NOT spring
NOT micronaut
etc...

**Comment by arik-dig** [comment]
talked with @shaykeren and we'll try to evaluate the modules deps WHEN triggering the run config - and only for that module.

**Comment by arik-dig** [comment]
fixed
