### ISSUE TITLE
ModulesDepsService need to update its mapName2Module if module configuration change

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#1594]
ModulesDepsService holds a map of module metadata. if user changes configuration the metadata need to update or revoked. 
for example user added library or changed versiopn

**Comment by arik-dig** [comment]
we can think of other solution: maybe not caching the Metadata but to evaluate it when needed on-the-fly.
need to check the performance impacts, and see how it behaves if modifying the build scripts (pom.xml and/or build.gradle files)

**Comment by shalom938** [comment]
current impact:

1. deciding if to show the user the hotfix button to add otel dependencies in a 'no observability' method. maybe the user added otel dependencies manually.
2. when executing a run configuration deciding if its SpringBootMicrometerTracing or MicronautModule, mayb euser added dependency manyally after the metadata was created.
