### ISSUE TITLE
Add PH events to when we show ANY of the new idle notifications

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1649]

**Comment by shalom938** [comment]
@doppleware 
There are events already

These are the events

Notifications.Show.DigmaHasntBeenRunningForAWhile
Notifications.Show.DigmaHasntBeenOpenedForAWhile
Notifications.Show.DigmaHasntBeenActivated

'ShowTypeform link clicked'
   details: origin=DigmaHasntBeenRunningForAWhile
'ShowTypeform link clicked'
   details: origin=DigmaHasntBeenOpenedForAWhile
'ShowTypeform link clicked'
   details: origin=DigmaHasntBeenActivated

'GoAway link clicked'
   details: origin=DigmaHasntBeenRunningForAWhile
'GoAway link clicked'
   details: origin=DigmaHasntBeenOpenedForAWhile
'GoAway link clicked'
   details: origin=DigmaHasntBeenActivated

Notifications.DigmaHasntBeenRunningForAWhile.clicked
Notifications.DigmaHasntBeenOpenedForAWhile.clicked
Notifications.DigmaHasntBeenActivated.clicked

you should see something like that
GoAway link clicked
Notifications.DigmaHasntBeenOpenedForAWhile.clicked
Notifications.Show.DigmaHasntBeenOpenedForAWhile
or
ShowTypeform link clicked
Notifications.DigmaHasntBeenRunningForAWhile.clicked
Notifications.Show.DigmaHasntBeenRunningForAWhile
