### ISSUE TITLE
Histogram document uses span Id instead of display name

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1708]
<img width="1621" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlVFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54304ea65801a27a485885184ca462f7b5b0134c/image.png" alt="image.png" />

**Comment by shalom938** [comment]
@kshmidt-digma 
in INSIGHTS/OPEN_HISTOGRAM
can you send the span display name ?

**Comment by kshmidt-digma** [comment]
@shalom938 
yes, it is possible to send `displayName` inside the `INSIGHTS/OPEN_HISTOGRAM` message

**Comment by shalom938** [comment]
@kshmidt-digma 
can you prepare a branch and let me know?

**Comment by kshmidt-digma** [comment]
@opoliarush will pick this task and notify you
