### ISSUE TITLE
Instrument ay task that ends with main()

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1807]
Anything that ends with *main() should be instrumented:

<img width="711" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTVsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0430daab72c6d6b2e48816232a0cca7da54aff96/image.png" alt="image.png" />

For example this event:

https://us.posthog.com/events/c2e3d50e-210a-4b8f-a864-608d63e153ee/2024-02-12T12%3A18%3A17.923000-08%3A00

**Comment by shalom938** [comment]
I don't understand the issue. we do that already.
