### ISSUE TITLE
Clicking on backend update notification (using deployment of type Helm) opens docker-extension app

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#1845]
connect to mellona and observe the behavior

**Comment by shalom938** [comment]
can't reproduce

[Screencast from 2024-02-26 17-22-05.webm](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/7877e769-20b5-4e2f-ab1d-88eb53199e50)

**Comment by shaykeren** [comment]
happened when deployment type is unknown
