### ISSUE TITLE
Workaround - add env variable to avoid failure because issue #1873

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1874]
See #1873 

Until we fix it, the following workaround should work but depends on Java version:

JDK_JAVA_OPTIONS=-noverify (for newer version)
or JAVA_TOOL_OPTIONS=“-Xverify:none” - older versions

**Comment by shalom938** [comment]
do you know what is newer and what is older? which versions?

**Comment by shalom938** [comment]
https://www.baeldung.com/java-lang-verifyerror
