### ISSUE TITLE
Request users to register after 2 weeks of usage

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1895]
If user did not yet register and FirstAssets and posthog property exists and is over two weeks old show a notification (IDE - Jetbrains notification)  to the user requesting to register

Text:
Digma is free! Please register to continue using it
We'd appreciate it if you register if you love using the product
Click the link below to enter your name and email
[Register]

Clicking the register link will open up the recent activity panel with the register option 

Show again once a day

**Comment by shalom938** [comment]
@kshmidt-digma 
https://github.com/digma-ai/digma-ui/issues/393

**Comment by shalom938** [comment]
see closed duplicate
https://github.com/digma-ai/digma-intellij-plugin/issues/1671
