### ISSUE TITLE
remove "scope" from summary tab and more changes

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#193]
The scope field is not relevant there any more 
The counter is wrong at the top of the tab
If there are no performance changes to show, hide the section

<img width="219" alt="image" src="https://user-images.githubusercontent.com/93863/206486555-815024d6-6323-4882-9542-dfd018122723.png">

**Comment by MykolaYaremchuk** [comment]
Scope label was already removed in scope of "Refresh all insights and errors button" commit (7c3436898a2051f41519fc9854b40885aec9b9bc)
![image](https://user-images.githubusercontent.com/117861250/206454683-e8f57f35-d5aa-4ff8-96cc-5b390b9f321e.png)
