### ISSUE TITLE
add a blackout period after branch change

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#1969]
we have a recurring fatal error of Outdated stub in index.
it probably happens after user changes branches. we catch bulk change and try to rebuild navigation discovery and get this error.
we can catch the branch change event and pause the navigation update for some time untill intellij refreshes the indexing.

this is related and maybe can be combined
https://github.com/digma-ai/digma-intellij-plugin/issues/1864

**Comment by shaykeren** [comment]
potential error prompt to the user
