### ISSUE TITLE
Incorrect unread count

### ISSUE THREAD

**Issue by kshmidt-digma** [digma-ai/digma-intellij-plugin#1985]
<img width="1512" alt="Screenshot 2024-03-22 at 16 39 01" src="https://github.com/digma-ai/digma-intellij-plugin/assets/119138536/b88967c4-827d-4f0c-aa60-45b9612b2e90">

Plugin commit: https://github.com/digma-ai/digma-intellij-plugin/commit/34a20cffe0a6e7dc7daf7c1330d55c898935a97e
BE commit: cec959046e9e3941410dbcf8d34e983bcf59d47e
Application: https://github.com/digma-ai/otel-sample-app-java

**Comment by borisermakof** [comment]
Fixed
