### ISSUE TITLE
Issue with spring and micrometer

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#2014]
User send the following issue:

1. Yes, I have clicked to add dependencies to use micrometer tracing
2. You will find stacktrace of the error in attached file
3. Java 21, spring-boot 3.2.2 with spring-boot-starter-jersey, spring-boot-starter-data-cassandra,spring-boot-starter-data-jpa, spring-boot-starter-data-jpa

Side note because I have BanDuplicateClasses policy, If I want to keep theses properties in my pom.xml It would require to exclude aopalliance:aopalliance from io.micrometer:micrometer-tracing-bridge-otel because it has same classes as in org.springframework:spring-aop. When testing digma I didn't exclude it to avoid introducing other issues.

[digma_fail (1).log.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGdpQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0ad4e57120f86737135a6a162428a7a18fb77a7/digma_fail%20%281%29.log.txt)

**Comment by shalom938** [comment]
The problem is non compatible dependencies between what we add and spring boot dependency management.
for some reason we added dependencies to maven including version and that caused incompatibility. for gradle we add the dependencies without version.
