### ISSUE TITLE
Add support for aggressive update notifications

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#2015]
Flow 1:
The user updates the plugin, and the backend version is below the `MINIMAL_BACKEND _VERSION` defined in the plugin itself.

Result: 
The following should happen:
 The UI (both recent activity and the insights panel) will have an empty state requiring the user to update the backend with a link that calls the 'update' link (the same one we have today)

Message: "Update Required" 
"Your Digma Engine is too old. Please update to use the latest features"

Flow 2:
The user updated the backend. The plugin gets back from the backend the information that the plugin version is too old to be functional. 

Message: "Plugin Update Required" 
"This version of the Digma plugin is too old. Please update to use the latest features"

Result:
The following should happen:
1. The UI (both recent activity and the insights panel) will have an empty state requiring the user to update the plugin with a link that calls the 'update' link (the same one we have today)

Flow 3:
The user did not update the backend or plugin but we think he needs to because he is past a minimal version
Result:

Update now view : "This version of the Digma plugin/backend is too old. Please update to use the latest features"

 A popup notification will appear every day (similar to the first insight) with the text: "Digma Update Required" "This Digma plugin/Engine is too old. please update it now using this link"

**Comment by ionuiux** [comment]
https://www.figma.com/file/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?type=design&node-id=5216-71552&mode=design&t=Q8Qvf7V3uNW4O9oY-11 - design mockup
