### ISSUE TITLE
Feedback from user is that method.include doesn't work with Digma

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#2063]
Good morning all - I am trying to use Digma locally to instrument a third party library (that I don't own). The library doesn't have any otel integration, but I've previously had some success with the otel Java agent and the otel.instrumentation.methods.include system property (from <https://opentelemetry.io/docs/languages/java/automatic/annotations/>). However, I'm having difficulty generating/receiving spans using this approach with Digma - is this something that should be possible?

**Comment by shalom938** [comment]
methods instrumentation works with digma.

adding the environment variable to the intellij run configuration always works.
OTEL_INSTRUMENTATION_METHODS_INCLUDE=ch.qos.logback.classic.Logger[filterAndLog_0_Or3Plus]\;mypackage.MyClass[myMethod2]

adding the system property will only work with intellij Application configuration
-Dotel.instrumentation.methods.include=mypackage.MyClass[myMethod]

its probably better to always use the environment variable OTEL_INSTRUMENTATION_METHODS_INCLUDE
