### ISSUE TITLE
Add support of digma.environment attribute without digma.environment.id

### ISSUE THREAD

**Issue by ohrebeniuk** [digma-ai/digma-intellij-plugin#2075]
Right now, if digma.environment is set, but digma.environment.is not set, all the traces go to the LOCAL environment.
We should change it to support digma.environment
<img width="1236" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0JtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1fba64cd35882756168f62e56663c038b033a05c/image.png" alt="image.png" />

**Comment by shaykeren** [comment]
```
   if digma.environment.id not exists and digma.environment not exists:
                 if test:
                     digma.environment=LOCAL-TESTS
                 else:
                     digma.environment=LOCAL
 if centralize:
     add digma.user.id=[CURRENT_USER_ID]


```
