### ISSUE TITLE
On creating new environment plugin asks me to register, but I'm already registered and logged in

### ISSUE THREAD

**Issue by ohrebeniuk** [digma-ai/digma-intellij-plugin#2079]
<img width="1635" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXRuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7f1c5b5af6d833c2b0c4557b6c4a998aef52d29/image.png" alt="image.png" />

**Comment by shaykeren** [comment]
on centralize deployment we should skip this step
https://github.com/digma-ai/digma-ui/issues/622

**Comment by shaykeren** [comment]
duplicate - https://github.com/digma-ai/digma-ui/issues/770
