### ISSUE TITLE
Can't add public environment to application environment variables

### ISSUE THREAD

**Issue by ohrebeniuk** [digma-ai/digma-intellij-plugin#2080]
I've created a new public environment, but I don't see a description of how to add this environment to my application.
<img width="1878" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejVuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e48dbd1cfe9f450997bb1456e9adfd73cff9f73b/image.png" alt="image.png" />

**Comment by shaykeren** [comment]
on centralize deployment we should skip this step
https://github.com/digma-ai/digma-ui/issues/622

**Comment by shaykeren** [comment]
related to https://github.com/digma-ai/digma-ui/issues/772

**Comment by shaykeren** [comment]
add "how to setup" to the environment hamburger menu
