### ISSUE TITLE
Extended observability hangs tests

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#2212]
STR:
Use petclinic repo
Run integration tests with extended observability
Observe tests stuck

Remove extended observability
Observe tests running

**Comment by shalom938** [comment]
@doppleware 
I can not reproduce, all tests are running ok with extended observability, i tried the petclinic java and kotlin




![image](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/b5e1070a-425d-49d2-8bea-b58550b893fe)

![Screenshot from 2024-06-13 12-48-41](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/80c8b93a-6803-4800-a3b3-42276ec4d487)

![Screenshot from 2024-06-13 12-47-34](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/0224f6d1-1594-4edc-a9b2-19259609bf59)

**Comment by shalom938** [comment]
I even see traces from the extended observability
![image](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/45c7a59d-8787-49f3-94a3-bd2f4b9c613e)
