### ISSUE TITLE
force update is not being triggered

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#2266]
4afd5060

**Comment by shalom938** [comment]
other users that have old backend and don't get ForceUpdate are on plugin version 2.0.319 or lower. in this version the local settings had no minimal backend version. it was added only in 2.0320.
[github](https://github.com/digma-ai/digma-intellij-plugin/commit/fd9fc57c497627d9b6aeddd617e9813c97e6a37c)

and force update does not return force update for the plugin
