### ISSUE TITLE
First time backend discovery events 

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#2290]
Requirement: 

We need to understand whether Digma is functional for the users, not only if they interact with it.
For that, we need to know about the backend status for: 

1. Assets discovered (True/False)
2. Insights discovered (True/False)
3. Issue Discovered (True/False)
4. Important issue discovered (True/False)

The plugin should periodically check the status of the above (every 5 minutes) until ALL conditions are met (1-4) 
and do the following upon the first time each of them is met:

1. Raise a posthoc event: These are new PostHog events 
2. Raise a UI notification:
For each check, we show only one notification to the UI. So if we have one check with more than one 'TRUE' for the first time, we will only show one notification. The notification we will show will be in reverse order for the items. So #4 (Important issue discovered) is the highest priority and #1 Asset discovered is the lowest. 
3. Update a state in the client to remember the status of this user
4. Add the four information statuses as attributes to each Posthog event for better filtering

UI notifications text:
1.. First assets discovered! Digma has received some data about your code. Click here to see the assets view.
2.  Digma has some initial analytics results.  Click here to see the list of assets and drill into any specific one to see more data. 
3.  Digma has some initial findings! Click here to view the issues and get more information.

-----IGNORE BELOW - OLD DESIGN --------

firstTimeInsightReceived
* any issue exists 
firstTimeAssetsReceived
* any span exists
firstTimeRecentActivityReceived
* any recent activity exists

should call  /CodeAnalytics/discovered-data (backend version >= 0.3.76) in the background every 5 min
if any of the response properties is false (assetFound, issueFound, recentActivityFound), should continue monitoring it until all of them are true.
should set corresponding posthog user properties (firstTimeInsightReceived, firstTimeAssetsReceived, firstTimeRecentActivityReceived)

for backward compatibility this logic should replace the current logic only when the backend version >= 0.3.76

**Comment by shaykeren** [comment]
new api added /CodeAnalytics/discovered-data
response example:
{
  "assetFound": true,
  "issueFound": true,
  "recentActivityFound": true
}

**Comment by shalom938** [comment]
@doppleware 
do we want 'plugin first-issue' ?

setFirstAssetsReceived is called when getAssetCategories and getAssetFilters and check api insightExists that check if there is a insight that is not brakedown ,usage and duration.
is that ok?

**Comment by shalom938** [comment]
in the notifications links, do we want to open the specific tab like issues,assets,analytics?
if yes it requires a work in the UI too because currently there is no way to do it

**Comment by doppleware** [comment]
@shalom938 plugin first-issue' is #3 on the list above
and yes we need to open a specific tab

**Comment by shalom938** [comment]
@doppleware I mean 'plugin first-issue' like 'plugin first-asset' , when viewed, not related to the backend discovery

**Comment by doppleware** [comment]
okay then yes we want it
