### ISSUE TITLE
Investigate user activation/installation failures

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#2385]
Install to connect
https://us.posthog.com/project/22368/insights/HccyHKwA

Connect to activate:
https://us.posthog.com/project/22368/insights/QtvNkPKP

1. Go over failed users in each dashboard. Try to summarize why they are failing (how many are failing on same reason)
Map any bugs/missing info.

Refer to this list of install errors:
[export.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVpRQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5eb9de855c8c5c1872d1011b2e61d40b932772e/export.xlsx)

2. Please refer to this list of users who didn't activate (but installed successfully) and find out what happened (is their project not supported, did they run the code etc.)

https://us.posthog.com/project/22368/cohorts/81563

**Comment by shalom938** [comment]
see attached list.
users that run SpringBootApplicationConfigurationType are ultimate users.we can try to support more ultimate configurations but this one works.

some users had plugin first-activity but never clicked a link.
you can see it here
https://us.posthog.com/project/22368/insights/Z9U8x6GV

some had plugin first-activity and insights viewed but never first asset
https://us.posthog.com/project/22368/insights/FEp55erm


these are the 21 from this list
https://us.posthog.com/project/22368/cohorts/81563

[no-activation-users.xlsx](https://github.com/user-attachments/files/16600295/no-activation-users.xlsx)
