### ISSUE TITLE
Layout  issues at 'Top usage' and 'Duration' insights 

### ISSUE THREAD

**Issue by asafchen-dig** [digma-ai/digma-intellij-plugin#242]
![image](https://user-images.githubusercontent.com/109060156/210216780-8efd499c-17f5-4655-9465-5e0cffc13521.png)

**Comment by MykolaYaremchuk** [comment]
Could you please provide more details? I see that you opened FluxMeasurementStore.CountSpanRecordsPerSecond file - but where can I find this file ? in which project? :)

**Comment by asafchen-dig** [comment]
In the BE repo:
https://github.com/digma-ai/digma-collector-backend
