### ISSUE TITLE
Add notification to guide anyone stuck after installation that uses the API #2421

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#2439]
After the first successful server connection, add a counter for 8 minutes.
If no code was run in the IDE and no usage is reported in the server show a notification ONE time:

Title: Run your code to use Digma
Content: Using the CLI to run your code? Here is how to connect to Digma (link)

**Comment by ionuiux** [comment]
Design mockup - https://www.figma.com/design/MxA95ZHK5NqGX4ptFQljRJ/%E2%AD%90-Design-System-3.0?node-id=12003-188564&t=QZmAGlEZxK46PkHN-11

**Comment by shalom938** [comment]
@ionuiux can you provide the icon ?
@doppleware what is the link to show?
