### ISSUE TITLE
UI layout bugs

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#244]
see attached screenshot
Also, there is a blank line between the environments and the scope, should fix it also

![Image](https://user-images.githubusercontent.com/1392692/210219517-12398c31-924a-4fbf-a253-a23e5fe88c71.png)

**Comment by MykolaYaremchuk** [comment]
How can I reproduce this issue?
I see that you opened FluxMeasurementStore.CountSpanRecordsPerSecond file - but where can I find this file ? in which project? :)
