### ISSUE TITLE
Notify active users to register in order to join the early access program  

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#2440]
Logic: People who are very engaged and using Digma's features would most likely want to get access to more issues/new features etc.

Conditions:
1. Not registered 
2. Two weeks from first installed
3. Have at least 5 days with meaningful actions in last three weeks. See https://app.zenhub.com/workspaces/digma-team-629081e5a37b4b0015ac6813/issues/gh/digma-ai/digma-intellij-plugin/2472

If these are true:
1. Show the notification to register for early access. The notification should say - Register to get early access to Digma capabilities 
  We have launched an innovator program to give you early access to new features, issues detection, UI drilldowns, and more. Sign up before to get into the list.

2. Bannel for the early access program. 

@ionuiux please design 1 and 2

**Comment by ionuiux** [comment]
1. Notification -
