### ISSUE TITLE
Click Digma link to open asset page in IDE

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#2511]
We should be able to have a URL scheme to allow the user to click a link on the local OS that will open the asset page in the Digma plugin (for OS that supports it) on a specific asset included in the link (span code object id) the page should be opened in the issues tab

**Comment by shalom938** [comment]
currently supports opening span 
supported url parameters:





show digma settings
"jetbrains://idea/settings?name=Digma Plugin"

show code object id not encoded - will probably work only from browser
"jetbrains://idea/digma/plugin?action=showAsset&codeObjectId=span:io.opentelemetry.tomcat-10.0$_$HTTP GET /owners/{ownerId}&environmentId=LOCAL#ID#42E6067A-E755-4211-BA0F-B2F84BA8B065"

show code object id encoded - will work from email and terminal
"jetbrains://idea/digma/plugin?action=showAsset&codeObjectId=span%3Aio.opentelemetry.tomcat-10.0%24_%24HTTP%20GET%20%2Fowners%2F%7BownerId%7D&environmentId=LOCAL%23ID%2342E6067A-E755-4211-BA0F-B2F84BA8B065"

from terminal
/home/shalom/.local/share/JetBrains/Toolbox/scripts/idea "jetbrains://idea/digma/plugin?action=showAsset&codeObjectId=span%3Aio.opentelemetry.tomcat-10.0%24_%24HTTP%20GET%20%2Fowners%2F%7BownerId%7D&environmentId=LOCAL%23ID%2342E6067A-E755-4211-BA0F-B2F84BA8B065"

**Comment by shalom938** [comment]
if the tool window is closed there will be a 5 seconds delay.
i need top do something to shorten it
