### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#2548]
The following has evaluated to null or missing: ==> dashboardEnvironment [in template "dashboard.ftl" at line 34, column 42] ---- Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)?? ---- ---- FTL stack trace ("~" means nesting-related): - Failed at: ${dashboardEnvironment} [in template "dashboard.ftl" at line 34, column 40] ----
string
event.throwableText
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...] at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134) at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:481) at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401) at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370) at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100) at freemarker.core.DollarVariable.accept(DollarVariable.java:63) at freemarker.core.Environment.visit(Environment.java:334) at freemarker.core.Environment.visit(Environment.java:340) at freemarker.core.Environment.process(Environment.java:313) at freemarker.template.Template.process(Template.java:383) at org.digma.intellij.plugin.dashboard.DashboardIndexTemplateBuilder.build(DashboardIndexTemplateBuilder.java:70) at org.digma.intellij.plugin.dashboard.DashboardService.buildIndexFromTemplate(DashboardService.java:50) at org.digma.intellij.plugin.dashboard.DashboardResourceHandler.processRequest(DashboardResourceHandler.java:38)

**Comment by opoliarush** [comment]
Fixed inside https://github.com/digma-ai/digma-intellij-plugin/issues/2533
