### ISSUE TITLE
docker-compose - should be persisted

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#2621]
motivation - to avoid downloading the latest version when docker-compose file is missing for the engine.

solution - 
when user upgrade its engine we should download and persist the docker-compose in both the tmp directory and ide persisted storage

**Comment by shalom938** [comment]
The docker compose file is bundled with the plugin.
it is unpacked to a persistence folder on the user's machine and reused without unpacking again or downloading.
see  org.digma.intellij.plugin.docker.ComposeFileProvider

when upgrading the local engine the plugin will download the latest compose file and replace the existing file.

if the file is deleted somehow the plugin will unpack the bundled compose file again when its necessary.
