### ISSUE TITLE
Not seeing full span name on hover in breakdown insight

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#275]
![Image](https://user-images.githubusercontent.com/93863/213444877-5b341342-11d9-4233-89cf-f1cca43d42bb.png)

**Comment by borisermakof** [comment]
@doppleware could you provide more specific STR to repro ? On ver 2.0.39 span name on hover fully visible

![image.png](https://images.zenhubusercontent.com/63f8d8e6a6b0081e026c69f6/90314aee-6fe7-468a-823a-907d38f2fbc6)

**Comment by doppleware** [comment]
It seems that this was fixed then, feel free to close

**Comment by borisermakof** [comment]
Not reproducible in 2.0.39
