### ISSUE TITLE
auto refresh changing UI issues #2

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#290]
* environments list is flickering
*  sometimes changing the environment is not working because of the auto-refresh
* sometimes refresh take us back to the previous environment
* environments are being duplicated

![Image](https://user-images.githubusercontent.com/1392692/216262623-de6b0b00-1b6c-4103-92bc-c090ee78e8e4.png)

* When moving the cursor between methods, refresh shows me the wrong insights, insights of the previous method

**Comment by shaykeren** [comment]
the attached view might help ....

**Comment by MykolaYaremchuk** [comment]
All issues are fixed in scope of `v2.0.22`
