### ISSUE TITLE
Support pycharm Idea

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#292]
*  Please document the steps for adding  a new idea

**Method Discovery**
`
method:[file path]$_$[class_name].[method_name] OR
method:[file path]$_$[function_name]
`
class_name is optional, therefore if the function exists not underclass only the function name should appear after the dollar seperator

NOTE: because we are not sure how the user opens the project, one/two folders up we need to get insights according to multiple different options of paths.

Example:
method_code_object: method:otel-sample-fastapi/database_validation.py$_$DomainValidator.validate_permissions
to get details about this code object,  multiple options of code objects should sent to Digma API

1. method:otel-sample-fastapi/database_validation.py$_$DomainValidator.validate_permissions
2. method:database_validation.py$_$DomainValidator.validate_permissions

**The rule is to split the path into all different sub-paths**
Example:
method:work_space_dir/foder1/folder2/app.py$_$my_method
1. work_space_dir/foder1/folder2/app.py$_$my_method
2. foder1/folder2/app.py$_$my_method
3. folder2/app.py$_$my_method
4. app.py$_$my_method

Span Discovery

otel-sample-fastapi/database_validation.py
span:database_validation$_$check_db_permission
span:database_validation$_$validating groups

**Comment by shalom938** [comment]
What about methods arguments ?

**Comment by shalom938** [comment]
what about analyticsService.getErrorsOfCodeObject(methodInfo.idWithType())
should also send multiple code object ids like the rules you mentioned ?

**Comment by shalom938** [comment]
@shaykeren  is this what you mean with multiple ids ?

    @Test
    fun testAdditionalIds(){
        val methodInfo = MethodInfo("my/test/file/path\$_\$myFunction","myFunction","myClass","my.namespace.MyClass","file://my/file.uri",10,listOf())
        val ids = PythonAdditionalIdsProvider().provideAdditionalIds(methodInfo)

        assert(ids.size == 3)
        assertContains(ids,"method:test/file/path\$_\$myFunction")
        assertContains(ids,"method:file/path\$_\$myFunction")
        assertContains(ids,"method:path\$_\$myFunction")
    }

**Comment by asafchen-dig** [comment]
## Tracer Name Discovery
In case the tracer name is defined with `__name__`, like this: 
``` python
tracer = trace.get_tracer(__name__)
...
with tracer.start_as_current_span("admin console"):
...
```
The instrumentation library may have up to 3 values - meaning multiple code object ids to the same span:
1. Use `__main__`, if the file contains this code `if__name__=='__main__'`
2. Use the module path from the file path:
    - Take the relative part of the file path (relative to the project folder or `venv` or `site-packages`)
    - Omit the `.py` file extension. 
    - Replace all `\` or `/` with `.`
3. Use the module path without its first segment, if it has more than one (= if it contains `.`)

**Comment by shalom938** [comment]
@asafchen-dig @shaykeren 
why does it matter if the file contains if__name__=='__main__' ?  that doesn't mean that __main__ is declared, __main__ is always declared. it only means that some code is testing its that is the main module.
if I understand correctly, when the tracer name is the __main__ variable you want to cover all options because there is no way to know its value.
So i will apply the three rules above if the tracer name is the __main__  variable,  but i think its doesn't matter if the file contains this statement if__name__=='__main__'

**Comment by shalom938** [comment]
examples of supported span patters, given two files:

project-root/myfolder/test/my_tracer_names.py
```
   MY_TRACER_NAME_IN_OTHER_FILE = "my tracer name in other file"
   MY_SPAN_NAME_IN_OTHER_FILE = "my span name in other file"
```

project-root/myfolder/test/my.py
```
MY_TRACER_NAME_CONST_TO_NAME_VAR = __name__
MY_TRACER_NAME_CONST = "my tracer name from const"
MY_SPAN_NAME_CONST = "my span name from const"

tracer_from_literal = trace.get_tracer("my literal tracer name")
tracer_from_name_var = trace.get_tracer(__name__)
tracer_from_const = trace.get_tracer(MY_TRACER_NAME_CONST)
tracer_from_const_in_other_file = trace.get_tracer(MY_TRACER_NAME_IN_OTHER_FILE)


def my_method1():
    with tracer_from_name_var.start_as_current_span(MY_SPAN_NAME_CONST):
        requests.get('https://xkcd.com/1906/')
## spans:
"__main__$_$my span name from const"
"myfolder.test.my$_$my span name from const"
"test.my$_$my span name from const"

def my_method2():
    with tracer_from_const.start_as_current_span(MY_SPAN_NAME_IN_OTHER_FILE):
        requests.get('https://xkcd.com/1906/')
## spans:
"my tracer name from const$_$my span name in other file"

def my_method3():
    with tracer_from_const_in_other_file.start_span("my span name literal"):
        requests.get('https://xkcd.com/1906/')
## spans:
"my tracer name in other file$_$my span name literal"

def my_method4():
    span_name_local = "my span name local var"
    with tracer_from_literal.start_span(span_name_local):
        requests.get('https://xkcd.com/1906/')
## spans:
"my literal tracer name$_$my span name local var"

def my_method5():
    span_name_local = "my span name local var"
    my_local_tracer = trace.get_tracer("my local tracer")
    with my_local_tracer.start_as_current_span(span_name_local):
        requests.get('https://xkcd.com/1906/')
## spans:
"my local tracer$_$my span name local var"

def my_method6():
    span_name_local = MY_SPAN_NAME_CONST
    my_local_tracer = trace.get_tracer(MY_TRACER_NAME_IN_OTHER_FILE)
    with my_local_tracer.start_as_current_span(span_name_local):
        requests.get('https://xkcd.com/1906/')
## spans
"my tracer name in other file$_$my span name from const"

def my_method7():
    span_name_local = MY_SPAN_NAME_CONST
    my_local_tracer = trace.get_tracer(MY_TRACER_NAME_CONST_TO_NAME_VAR)
    with my_local_tracer.start_as_current_span(span_name_local):
        requests.get('https://xkcd.com/1906/')
## spans:
"__main__$_$my span name from const"
"myfolder.test.my$_$my span name from const"
"test.my$_$my span name from const"


def my_method8():
    span_name_local = MY_SPAN_NAME_CONST
    with trace.get_tracer("my locally created tracer").start_as_current_span(span_name_local):
        requests.get('https://xkcd.com/1906/')
## spans:
"my locally created tracer$_$my span name from const"

def my_method9():
    span_name_local = MY_SPAN_NAME_CONST
    with trace.get_tracer(MY_TRACER_NAME_CONST_TO_NAME_VAR).start_as_current_span(span_name_local):
        requests.get('https://xkcd.com/1906/')
## spans
"__main__$_$my span name from const"
"myfolder.test.my$_$my span name from const"
"test.my$_$my span name from const"

def my_method10():
    span_name_local = __name__
    my_local_tracer = trace.get_tracer(MY_TRACER_NAME_CONST_TO_NAME_VAR)
    with my_local_tracer.start_as_current_span(span_name_local):
        requests.get('https://xkcd.com/1906/')
## spans:
"__main__$_$__name__"
"myfolder.test.my$_$__name__"
"test.my$_$__name__"


```

**Comment by shalom938** [comment]
@shaykeren 
Note:
If python interpreter is not configured correctly span discovery will not work

**Comment by shalom938** [comment]
I saw also something like that somewhere, the name value is a binary expression. its not supported.

```
 name = span_name or TracingDecoratorOptions.naming_scheme(func_or_class)
            with tracer.start_as_current_span(name, record_exception=record_exception) as span:
                _set_semantic_attributes(span,func_or_class)
                _set_attributes(span, TracingDecoratorOptions.default_attributes)
                _set_attributes(span, attributes)
                return func_or_class(*args, **kwargs)
```

**Comment by shaykeren** [comment]
> python interpreter is not configured correctly span discovery will not work.
> 
> for example if the project is opened and interpreter is not configured , span navigation will not be built and documents that were opened will not contain span discovery. if the interpreter is configured and then closing and opening a file it will now have spans. but span navigation will not fix it self unless the project is restarted. maybe there is a way to cache the event when configuring interpreter and rebuild the span navigation.

sure

**Comment by shaykeren** [comment]
> > python interpreter is not configured correctly span discovery will not work.
> > for example if the project is opened and interpreter is not configured , span navigation will not be built and documents that were opened will not contain span discovery. if the interpreter is configured and then closing and opening a file it will now have spans. but span navigation will not fix it self unless the project is restarted. maybe there is a way to cache the event when configuring interpreter and rebuild the span navigation.
> 
> I'll open a task about the span navigation, we'll discuss it in a different thread see #337

**Comment by shaykeren** [comment]
> 

@asafchen-dig need your reference

**Comment by shaykeren** [comment]
> @asafchen-dig @shaykeren why does it matter if the file contains `if __name__=='__main__'` ? that doesn't mean that `__main__` is declared, `__main__` is always declared. it only means that some code is testing its that is the main module. if I understand correctly, when the tracer name is the `__main__` variable you want to cover all options because there is no way to know its value. So i will apply the three rules above if the tracer name is the `__main__` variable, but i think its doesn't matter if the file contains this statement `if __name__=='__main__'`

@asafchen-dig your reference is needed here

**Comment by shaykeren** [comment]
> examples of supported span patters, given two files:
> 
> project-root/myfolder/test/my_tracer_names.py
> 
> ```
>    MY_TRACER_NAME_IN_OTHER_FILE = "my tracer name in other file"
>    MY_SPAN_NAME_IN_OTHER_FILE = "my span name in other file"
> ```
> 
> project-root/myfolder/test/my.py
> 
> ```
> MY_TRACER_NAME_CONST_TO_NAME_VAR = __name__
> MY_TRACER_NAME_CONST = "my tracer name from const"
> MY_SPAN_NAME_CONST = "my span name from const"
> 
> tracer_from_literal = trace.get_tracer("my literal tracer name")
> tracer_from_name_var = trace.get_tracer(__name__)
> tracer_from_const = trace.get_tracer(MY_TRACER_NAME_CONST)
> tracer_from_const_in_other_file = trace.get_tracer(MY_TRACER_NAME_IN_OTHER_FILE)
> 
> 
> def my_method1():
>     with tracer_from_name_var.start_as_current_span(MY_SPAN_NAME_CONST):
>         requests.get('https://xkcd.com/1906/')
> ## spans:
> "__main__$_$my span name from const"
> "myfolder.test.my$_$my span name from const"
> "test.my$_$my span name from const"
> 
> def my_method2():
>     with tracer_from_const.start_as_current_span(MY_SPAN_NAME_IN_OTHER_FILE):
>         requests.get('https://xkcd.com/1906/')
> ## spans:
> "my tracer name from const$_$my span name in other file"
> 
> def my_method3():
>     with tracer_from_const_in_other_file.start_span("my span name literal"):
>         requests.get('https://xkcd.com/1906/')
> ## spans:
> "my tracer name in other file$_$my span name literal"
> 
> def my_method4():
>     span_name_local = "my span name local var"
>     with tracer_from_literal.start_span(span_name_local):
>         requests.get('https://xkcd.com/1906/')
> ## spans:
> "my literal tracer name$_$my span name local var"
> 
> def my_method5():
>     span_name_local = "my span name local var"
>     my_local_tracer = trace.get_tracer("my local tracer")
>     with my_local_tracer.start_as_current_span(span_name_local):
>         requests.get('https://xkcd.com/1906/')
> ## spans:
> "my local tracer$_$my span name local var"
> 
> def my_method6():
>     span_name_local = MY_SPAN_NAME_CONST
>     my_local_tracer = trace.get_tracer(MY_TRACER_NAME_IN_OTHER_FILE)
>     with my_local_tracer.start_as_current_span(span_name_local):
>         requests.get('https://xkcd.com/1906/')
> ## spans
> "my tracer name in other file$_$my span name from const"
> 
> def my_method7():
>     span_name_local = MY_SPAN_NAME_CONST
>     my_local_tracer = trace.get_tracer(MY_TRACER_NAME_CONST_TO_NAME_VAR)
>     with my_local_tracer.start_as_current_span(span_name_local):
>         requests.get('https://xkcd.com/1906/')
> ## spans:
> "__main__$_$my span name from const"
> "myfolder.test.my$_$my span name from const"
> "test.my$_$my span name from const"
> 
> 
> def my_method8():
>     span_name_local = MY_SPAN_NAME_CONST
>     with trace.get_tracer("my locally created tracer").start_as_current_span(span_name_local):
>         requests.get('https://xkcd.com/1906/')
> ## spans:
> "my locally created tracer$_$my span name from const"
> 
> def my_method9():
>     span_name_local = MY_SPAN_NAME_CONST
>     with trace.get_tracer(MY_TRACER_NAME_CONST_TO_NAME_VAR).start_as_current_span(span_name_local):
>         requests.get('https://xkcd.com/1906/')
> ## spans
> "__main__$_$my span name from const"
> "myfolder.test.my$_$my span name from const"
> "test.my$_$my span name from const"
> 
> def my_method10():
>     span_name_local = __name__
>     my_local_tracer = trace.get_tracer(MY_TRACER_NAME_CONST_TO_NAME_VAR)
>     with my_local_tracer.start_as_current_span(span_name_local):
>         requests.get('https://xkcd.com/1906/')
> ## spans:
> "__main__$_$__name__"
> "myfolder.test.my$_$__name__"
> "test.my$_$__name__"
> ```

@asafchen-dig your reference is needed here

**Comment by asafchen-dig** [comment]
> @asafchen-dig @shaykeren why does it matter if the file contains `if __name__=='__main__'` ? that doesn't mean that `__main__` is declared, `__main__` is always declared. it only means that some code is testing its that is the main module. if I understand correctly, when the tracer name is the `__main__` variable you want to cover all options because there is no way to know its value. So i will apply the three rules above if the tracer name is the `__main__` variable, but i think its doesn't matter if the file contains this statement `if __name__=='__main__'`

Those 3 rules are for the case when the tracer name is `__name__`  (not `__main__`) and statement `if __name__=='__main__'` exists. In that case the `__name__` parameter may have different values depending whether or not the user runs the files itself or a different file that imports it.

**Comment by asafchen-dig** [comment]
> examples of supported span patters, given two files:
> 
> project-root/myfolder/test/my_tracer_names.py
> 
> ```
>    MY_TRACER_NAME_IN_OTHER_FILE = "my tracer name in other file"
>    MY_SPAN_NAME_IN_OTHER_FILE = "my span name in other file"
> ```
> 
> project-root/myfolder/test/my.py
> 
> ```
> MY_TRACER_NAME_CONST_TO_NAME_VAR = __name__
> MY_TRACER_NAME_CONST = "my tracer name from const"
> MY_SPAN_NAME_CONST = "my span name from const"
> 
> tracer_from_literal = trace.get_tracer("my literal tracer name")
> tracer_from_name_var = trace.get_tracer(__name__)
> tracer_from_const = trace.get_tracer(MY_TRACER_NAME_CONST)
> tracer_from_const_in_other_file = trace.get_tracer(MY_TRACER_NAME_IN_OTHER_FILE)
> 
> 
> def my_method1():
>     with tracer_from_name_var.start_as_current_span(MY_SPAN_NAME_CONST):
>         requests.get('https://xkcd.com/1906/')
> ## spans:
> "__main__$_$my span name from const"
> "myfolder.test.my$_$my span name from const"
> "test.my$_$my span name from const"
> 
> def my_method2():
>     with tracer_from_const.start_as_current_span(MY_SPAN_NAME_IN_OTHER_FILE):
>         requests.get('https://xkcd.com/1906/')
> ## spans:
> "my tracer name from const$_$my span name in other file"
> 
> def my_method3():
>     with tracer_from_const_in_other_file.start_span("my span name literal"):
>         requests.get('https://xkcd.com/1906/')
> ## spans:
> "my tracer name in other file$_$my span name literal"
> 
> def my_method4():
>     span_name_local = "my span name local var"
>     with tracer_from_literal.start_span(span_name_local):
>         requests.get('https://xkcd.com/1906/')
> ## spans:
> "my literal tracer name$_$my span name local var"
> 
> def my_method5():
>     span_name_local = "my span name local var"
>     my_local_tracer = trace.get_tracer("my local tracer")
>     with my_local_tracer.start_as_current_span(span_name_local):
>         requests.get('https://xkcd.com/1906/')
> ## spans:
> "my local tracer$_$my span name local var"
> 
> def my_method6():
>     span_name_local = MY_SPAN_NAME_CONST
>     my_local_tracer = trace.get_tracer(MY_TRACER_NAME_IN_OTHER_FILE)
>     with my_local_tracer.start_as_current_span(span_name_local):
>         requests.get('https://xkcd.com/1906/')
> ## spans
> "my tracer name in other file$_$my span name from const"
> 
> def my_method7():
>     span_name_local = MY_SPAN_NAME_CONST
>     my_local_tracer = trace.get_tracer(MY_TRACER_NAME_CONST_TO_NAME_VAR)
>     with my_local_tracer.start_as_current_span(span_name_local):
>         requests.get('https://xkcd.com/1906/')
> ## spans:
> "__main__$_$my span name from const"
> "myfolder.test.my$_$my span name from const"
> "test.my$_$my span name from const"
> 
> 
> def my_method8():
>     span_name_local = MY_SPAN_NAME_CONST
>     with trace.get_tracer("my locally created tracer").start_as_current_span(span_name_local):
>         requests.get('https://xkcd.com/1906/')
> ## spans:
> "my locally created tracer$_$my span name from const"
> 
> def my_method9():
>     span_name_local = MY_SPAN_NAME_CONST
>     with trace.get_tracer(MY_TRACER_NAME_CONST_TO_NAME_VAR).start_as_current_span(span_name_local):
>         requests.get('https://xkcd.com/1906/')
> ## spans
> "__main__$_$my span name from const"
> "myfolder.test.my$_$my span name from const"
> "test.my$_$my span name from const"
> 
> def my_method10():
>     span_name_local = __name__
>     my_local_tracer = trace.get_tracer(MY_TRACER_NAME_CONST_TO_NAME_VAR)
>     with my_local_tracer.start_as_current_span(span_name_local):
>         requests.get('https://xkcd.com/1906/')
> ## spans:
> "__main__$_$__name__"
> "myfolder.test.my$_$__name__"
> "test.my$_$__name__"
> ```

The file does not contain the statement `if__name__=='__main__'`, so all the span id possibilities that start with `__main__$_$` should not be there

**Comment by asafchen-dig** [comment]
I accidentally closed the issue

**Comment by shalom938** [comment]
> > @asafchen-dig @shaykeren why does it matter if the file contains `if __name__=='__main__'` ? that doesn't mean that `__main__` is declared, `__main__` is always declared. it only means that some code is testing its that is the main module. if I understand correctly, when the tracer name is the `__main__` variable you want to cover all options because there is no way to know its value. So i will apply the three rules above if the tracer name is the `__main__` variable, but i think its doesn't matter if the file contains this statement `if __name__=='__main__'`
> 
> Those 3 rules are for the case when the tracer name is `__name__` (not `__main__`) and statement `if __name__=='__main__'` exists. In that case the `__name__` parameter may have different values depending whether or not the user runs the files itself or a different file that imports it.

@asafchen-dig  Yes I meant `__name__` not `__main__`, still asking why does it matter if the file contains, ``if __name__=='__main__`

**Comment by shalom938** [comment]
@asafchen-dig @shaykeren 
I understand the rules for span id if the value for the instrumentation library is the `__name__` variable.
i don't understand why does it matter if the file contains this statement: `if __name__==__main__`.
the file can also contains this statement `if __name__==some-name`, and maybe the file does not contain any of these statement and still the value of `__name__` is `__main__`.
I think the three rules should always apply if the value for instrumentation library is the `__name__` variable.

**Comment by shalom938** [comment]
@asafchen-dig @shaykeren 
Why do we need to consider a venv folder when computing object ids from paths?
as i understand the virtual environment name is arbitrary and i can call it whatever i want. from what i see there are python files only under site-packages directly. other directories and files under the virtual environment are not python files.
we probably need to consider only site-packages. 
what do you think?

**Comment by shalom938** [comment]
@shaykeren 
do we need to build span navigation for spans in files outside the project? for example files under site-packages?
for example spans in 
.venv/lib/python3.10/site-packages/opentelemetry/instrumentation/digma/trace_decorator.py

**Comment by shalom938** [comment]
@shaykeren 
if two spans have the same span id the navigation is unpredictable.
