### ISSUE TITLE
Jetbrains plugin does not handle server disconnect correctly

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#303]
STR:
1. Run Digma backend. 
2. Open the IDE on a function that has insights and decorators
3. Stop the Digma backend
4. Decorators will continue to appear, the insight tab will say 'no insights'.

![Image](https://user-images.githubusercontent.com/93863/217654208-5226cd91-bf91-481f-8a44-e5cc4ce7ef9e.png)

Expected behavior:
In the sidepanel we should see a message that it is unable to communicate with Digma. The message should also contain the Digma address and port it is trying to reach. It should also suggest: Please check if the Digma backend is up.
All decorators should not be shown.

Please make sure not to show an error notification on disconnect as that can just annoy the user.

As a reference, see the vscode behavior:

![Image](https://user-images.githubusercontent.com/93863/217655656-d83b369b-6392-43e0-adc5-b86a147bedc4.png)

**Comment by MykolaYaremchuk** [comment]
we already have this message in Jetbrains on case when connection is lost:

**Comment by MykolaYaremchuk** [comment]
cannot reproduce this issue
