### ISSUE TITLE
Add links to endpoint in N+1, Bottleneck, Usage and Scale insights

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#304]
See example below:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/93863/217665640-582da17d-efbf-4fe0-968e-e2b46bdc869e.png">

This is already implemented in vscode - the server returns the codeobjectid if exists.

**Comment by borisermakof** [comment]
Chnged SP to 2
1 insight wasnt implemented at all (Scaling Root Cause Insight)
1 needed to be fully reworked because view was too obsolete
