### ISSUE TITLE
Plugin identifies java file as 'non supported object'

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#307]
STR:
Clone the Spring Framework repo from [here](https://github.com/spring-projects/spring-framework)

Go to the file UrlAssertionTets.java and the class SimpleController. See the below message

![Image](https://user-images.githubusercontent.com/93863/217682335-55c9ef6d-a644-4fdb-bba7-b546b6a7f7bc.png)

**Comment by arik-dig** [comment]
@doppleware I think that you have some IDE and/or SDK problem.
so up until fixing it, ANY JAVA file would be seen as Non supported.

**Comment by MykolaYaremchuk** [comment]
@doppleware on your example I can see opened test file UrlAssertionTests.java, 
we don't support files under _`test`_ folder.

org.digma.intellij.plugin.editor.EditorEventsHandler#isRelevantFile
org.digma.intellij.plugin.idea.psi.java.JavaLanguageUtils#isRelevantFile


if you faced the same problem for other files which are not under _`test`_ folder that my assumption is that you had some configuration issues which Arik mentioned above

**Comment by shalom938** [comment]
@arik-dig @doppleware  Test classes are intentionally not supported, we check if file is under test folder.

**Comment by doppleware** [comment]
Hey @shalom938 What is the reason for the limitation?
