### ISSUE TITLE
Weird layout of "Applying the new time filter"

### ISSUE THREAD

**Issue by asafchen-dig** [digma-ai/digma-intellij-plugin#313]
![Image](https://user-images.githubusercontent.com/109060156/218316347-fd25b874-c136-4c8e-b80e-28e03aaabda3.png)

**Comment by MykolaYaremchuk** [comment]
This issue was fixed in scope of release `v2.0.30`
https://github.com/digma-ai/digma-intellij-plugin/releases/tag/v2.0.30
