### ISSUE TITLE
Navigation schema change continued - summary view

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#326]
https://www.figma.com/proto/ncRV3XUn1VltctY8LjlJFX/Digma-Design-System?node-id=275%3A16343&scaling=min-zoom&page-id=15%3A3461&starting-point-node-id=275%3A26214&show-proto-sidebar=1

![image.png](https://images.zenhubusercontent.com/63ec76164ec7e010c1af91fc/42dd9cb7-4b59-49b1-a472-8c386a61c260)

yellow area - clicking on the home button will open the summary view (panel)
Remove the summary tab - the summary view will not be located inside a tab, it will take the whole area

home button behavior: 
for now, this is a toggle button between - 
tabs view (insights and errors) and summary view (panel)

refresh button should refresh the currently selected view (tabs/summary)

**Explanation from Roni (14th of March 2023):**
"so imagine that when you click somewhere in the code it selects that code object
So we don't show dashboard
If you click dashboard it shows the dashboard tab and hides the insight and errors tabs
And the code object is no longer selected so doesn't appear in the black strip above
So together dashboard with (assets and errors tab) cannot exist on the same screen (only display them conditionaly)
"
[Uploading... image.png]

**Comment by shaykeren** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Digma-Team-629081e5a37b4b0015ac6813/issues/digma-ai/digma-intellij-plugin/326?planning-poker) with Zenhub @arik-dig @asafchen-dig @borisermakof @kshmidt-digma @MykolaYaremchuk

**Comment by MykolaYaremchuk** [comment]
Hi @doppleware @shaykeren how error links should work on case of Dashboard view? 
when user clicked on some error link from the Dashboard - user should be navigated to "Error details" tab as we have it for now?

so as result actual Dashboard view should be replaced with "Insights" and "Error Details" tabs?

**Comment by MykolaYaremchuk** [comment]
looks like I've found appropriate design:
![image.png](https://images.zenhubusercontent.com/64060bd36f1a6530e79af907/2082b8c5-5b55-48db-98e6-171ca272571c)
so should tab name "Dashboard" disappear in this case?

**Comment by shaykeren** [comment]
already done
