### ISSUE TITLE
java - no span navigation in java , the span ids that the backend sends are not what we discover

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#339]
please consult with @shalom938 on this one...I found that there is not span navigation

additional info(from @shalom938 ):
The backend sends things like that , we don't build span ids like that
io.opentelemetry.hibernate-6.0$_$SELECT
io.opentelemetry.spring-data-1.8$_$OwnerRepository.findByLastName
io.opentelemetry.spring-webmvc-6.0$_$Render owners/findOwners
io.opentelemetry.spring-webmvc-6.0$_$Render owners/ownersList
we build with these
String WITH_SPAN_INST_LIBRARY_1 = "io.opentelemetry.spring-boot-autoconfigure";
String WITH_SPAN_INST_LIBRARY_2 = "io.opentelemetry.opentelemetry-instrumentation-annotations-1.16";
String WITH_SPAN_INST_LIBRARY_3 = "io.quarkus.opentelemetry";
String WITH_SPAN_INST_LIBRARY_4 = "io.micronaut.code";

**Comment by arik-dig** [comment]
@shaykeren , @shaykeren not sure what we can do about it.
the known WITH_SPAN are used just for WithSpan.
