### ISSUE TITLE
Show lens for unreachable code

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#347]
If it takes time lets do only Java for now and open additional tasks for the others
The lens name is 'Never Reached'

**Comment by doppleware** [comment]
This should only be displayed on functions we know we can get data from (e.g there is a span/endpoint definition).
For example, in this case we don't really know if it wasn't reached or not since we don't have instrumentation:

<img width="305" alt="image" src="https://user-images.githubusercontent.com/93863/231541309-55a00520-d7aa-4fb3-b05a-b93616b919ea.png">

**Comment by arik-dig** [comment]
@borisermakof , @MykolaYaremchuk  in my opinion we better wait for issue #280 to be resolved - that way we could use the new model - insights PER method

**Comment by doppleware** [comment]
<img width="263" alt="image" src="https://user-images.githubusercontent.com/93863/231742679-bf65b606-fd21-43b8-bcc7-f5eb6021e8e8.png">
