### ISSUE TITLE
processing insights view

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#353]
processing insights view
https://www.figma.com/file/knBV9hsfk9Au7mDQdFAFea/READY-TO-DEV?node-id=167%3A51634&t=1x43U83odFHeH4tI-1

Here's screenshot from Figma:
![image.png](https://images.zenhubusercontent.com/63fb6db2b75a9adf3c51dd6b/2d5e0765-a165-4b86-bcdd-85d269452928)

**Comment by shaykeren** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Digma-Team-629081e5a37b4b0015ac6813/issues/digma-ai/digma-intellij-plugin/353?planning-poker) with Zenhub @arik-dig @asafchen-dig @borisermakof @kshmidt-digma @MykolaYaremchuk

**Comment by arik-dig** [comment]
goes together with issue #389, see https://github.com/digma-ai/digma-intellij-plugin/issues/389#issuecomment-1475236433
