### ISSUE TITLE
Navigation schema change - target icon (code navigation) 

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#375]
created from issue #https://github.com/digma-ai/digma-collector-backend/issues/593#issuecomment-1452329458

Figma: 
https://www.figma.com/file/knBV9hsfk9Au7mDQdFAFea/READY-TO-DEV?node-id=1%3A4206&t=tPuUR6s5Vw2Gh2Zu-0

1. We would want to present the links only after drilling into individual assets, so we should be fine to use SpanFlows for now even though it's not queriable. It also means we should consider separating this into a new API that returns the span flow in its entirety.
2. Ultimately, we'll want to merge the client info on span links with the server info. Basically, the client knows which spans in the flow are 'client discoverable' and the server knows which ones are 'server discoverable'  (contain method code object id) and only by combining these infos can we know what is the closest span to show.

API already exists consult with @arik-dig 

Notice the 'target' icon, if there is only a single direct link (to this asset itself, this is what we would see)
<img width="307" alt="image" src="https://user-images.githubusercontent.com/93863/222517190-a8b8518d-d1ac-4b35-80d3-fd0181e416f4.png">

If there are no 'direct' links we would see a dropdown with the related links:
<img width="289" alt="image" src="https://user-images.githubusercontent.com/93863/222517428-9ee9d1b6-3746-46f0-9516-f4a0790ce0bd.png">

<img width="366" alt="image" src="https://user-images.githubusercontent.com/93863/222517545-98bd2d73-76a1-48cd-bde4-2d045eb55bbc.png">

**Comment by arik-dig** [comment]
backend is ready, see [PR 719 - Feature/parent span code navigation](https://github.com/digma-ai/digma-collector-backend/pull/719)
