### ISSUE TITLE
No context menu when recent activity is open

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#379]
The Observability stills the focus, you can see in the video that after its opened I'm trying to right click and open the context menu but its not possible, and the tabs don't gain focus when clicking on them, see the blue line under the title, when Observability is closed its back to normal.
[Screencast from 2023-03-13 06-03-58.webm](https://user-images.githubusercontent.com/1392692/224701545-aa7358b3-511c-4592-8538-c995fb819b1b.webm)

//might be related to OS
[Slack Message](https://digmatechnicalteam.slack.com/archives/D03A0AE0V2S/p1678680771985779)

**Comment by shaykeren** [comment]
@shalom938 what OS are you using?

**Comment by shalom938** [comment]
Linux

**Comment by shalom938** [comment]
With Gnome desktop

**Comment by shalom938** [comment]
I tested on another linux machine and there is no problem, somehow its only on my machine

**Comment by shalom938** [comment]
@shaykeren 
I tested on linux Manjaro and there is no problem.
it only happens on my machine , Opensuse tumbleweed with gnome desktop.
it may be related to this gnome bug which i am also experiencing on my machine:
https://gitlab.gnome.org/GNOME/mutter/-/issues/2635

I think you can close this issue as not reproducible.
