### ISSUE TITLE
Bug/IntelliJ IDEA - code lenses are not shown

### ISSUE THREAD

**Issue by arik-dig** [digma-ai/digma-intellij-plugin#380]
### Plugin version
**2.0.38**

Expecting to see Error Hotpot
![image.png](https://images.zenhubusercontent.com/63fb6db2b75a9adf3c51dd6b/bcb84b88-94e9-4282-83d5-a19553415304)

But do not see:
![image.png](https://images.zenhubusercontent.com/63fb6db2b75a9adf3c51dd6b/f8d474fd-35d7-4949-94f7-d5513c2c3a58)

Also do not see High Usage, while seeing such insight:
![image.png](https://images.zenhubusercontent.com/63fb6db2b75a9adf3c51dd6b/180191f2-cf43-4c89-bb34-372fd5e520da)

**Comment by arik-dig** [comment]
seems like its happening when opening the IDE and that file is open and chosen.
if I close the file and open it again, I do see the lenses.

**Comment by arik-dig** [comment]
looks related to Issue #373

**Comment by shalom938** [comment]
are you using 2.0.38 or 39 ?
my latest commit is 39, and i have code lens


![image](https://user-images.githubusercontent.com/170266/224748631-89833b63-ee1b-4b60-a2cc-98883f331d08.png)
![image](https://user-images.githubusercontent.com/170266/224748690-1b6f6d5c-27b9-4efa-948c-009a0fd593cd.png)

**Comment by shalom938** [comment]
should be fixed in 2.0.39
