### ISSUE TITLE
Add shortcut to add instrumentation to Java function

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#382]
@doppleware commented on [Sun Feb 19 2023](https://github.com/digma-ai/digma-collector-backend/issues/621)

Expected result: Have a button 'add instrumentation' available when selecting a function that doesn't have instrumentation that adds the annotation. 

How to demo:
Navigate to a code location (method) that is not an endpoint and has no spans/traces that can be discovered from the client side.

The sidepane should present an option to 'observe this function'.
Clicking the button should add the 'WithSpan' annotation.

If there is a missing dependency for opentelemetry.annotations, there should be an option to 'autofix' which would add the dependency to the build or pom file.

### A.K.A SubTask 2

![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/83f742a1-0406-4ded-98bf-cb003d1d7793)

### A.K.A SubTask 3

![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/0c2c30b1-5746-42f1-8149-abdc47d4eb79)

The last state is not included in this story, but goes to illustrate that after we add the span annotation we expect to see an empty state that asks the user to generate data.

**Comment by shaykeren** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Digma-Team-629081e5a37b4b0015ac6813/issues/digma-ai/digma-intellij-plugin/382?planning-poker) with Zenhub @arik-dig @asafchen-dig @borisermakof @kshmidt-digma @MykolaYaremchuk

**Comment by arik-dig** [comment]
goes together with issue #389, see https://github.com/digma-ai/digma-intellij-plugin/issues/389#issuecomment-1475236433

**Comment by arik-dig** [comment]
@doppleware how should the screen look like if really NO insights at all (including no errors) ?
can we get mockup?

**Comment by arik-dig** [comment]
@doppleware how should the screen look like if really NO insights at all (including no errors) ?
can we get mockup?

**Comment by doppleware** [comment]
For now it can appear as is (as an insight card)

**Comment by doppleware** [comment]
Here it is
<img width="379" alt="image" src="https://user-images.githubusercontent.com/93863/226942122-07244517-023c-45f0-a0c7-b454913ae461.png">

**Comment by arik-dig** [comment]
@shaykeren , @doppleware , can you please grab the SVG icon of **NoObservability**, and attach it in here?

**Comment by arik-dig** [comment]
@doppleware I guess we gonna need SVG file so we could support different colors based on the Theme
