### ISSUE TITLE
Create empty state for no data yet

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#389]
![no_data_yet_dark](https://user-images.githubusercontent.com/1392692/226327683-febcbb18-3670-4923-a595-a06bc2f1f333.svg)
https://www.figma.com/file/9WRmS8uKjUIv45ldWun2pt/UI---Shared?t=QB6Ruet3ufiX1CfH-0

### Sub Task 1
State should be shown if:
1. Method is either an endpoint or span exists in method
2. No data about this code location

We have two forms for this state.
One is when we have no info at all (errors or data about any span):

![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/c7eb52b5-a3ad-42df-859e-2c133631f4c0)

### Sub Task 2

Or if we're missing info only for a specific span/endpoint (but we have other data)
Note: In the below screenshot we are missing the span 'group' under which this message appears.

![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/b55bc568-f954-4f75-8730-9cb4ada20200)

**Comment by arik-dig** [comment]
@doppleware maybe we should add to assets view (done within the plugin itself):
spans that are discovered on the client side, but are not known to the backend?

**Comment by shaykeren** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Digma-Team-629081e5a37b4b0015ac6813/issues/digma-ai/digma-intellij-plugin/389?planning-poker) with Zenhub @arik-dig @asafchen-dig @borisermakof @kshmidt-digma @MykolaYaremchuk

**Comment by shaykeren** [comment]
| Client Discovered Spans  | KnownByServer | Has Insights                                                    | More Info |
| ------------------------- | ---------------- | -------------------------------------------|--------------|
|        span1, span2              |            No            |     No  insights / errors insights only             | span1 and span2 should have No data receive yet insight item |
|        span1, span2               |       at least one of the spans is  known by the server | No  insights |  processing insights message should be shown |
|  - |

**Comment by arik-dig** [comment]
@doppleware look at subtask, the title "No Observability" is bit confusing, isn't it?
If I may suggest maybe it should be "No Data Yet"?

**Comment by doppleware** [comment]
Yes its a mistake in the prototype

**Comment by shaykeren** [comment]
see attached image:
![image](https://user-images.githubusercontent.com/1392692/226912004-5ec720fb-dd45-4b0c-95ea-4ee55c7504e6.png)
