### ISSUE TITLE
UI issues/New Environment navigation - not enough space between the lines

### ISSUE THREAD

**Issue by arik-dig** [digma-ai/digma-intellij-plugin#392]
### Since
PR #391

### Version
Intellij 2.0.39

### 2 UI issues:

1) There's not enough space between the lines of environments
2) when environment name is long 2 thing happen:
  2a) the icon of data disappears
  2b) the name is cut and even no tooltip to see the fullname

![image](https://user-images.githubusercontent.com/104715391/226161673-1543458b-80a3-4932-8af2-a28de971e41b.png)

**Comment by shaykeren** [comment]
see attached image for other issues related to the text size 
the following issue was reproduced in @shalom938  machine.
Shalom is using different text scaling (os settings) 
![image (16)](https://user-images.githubusercontent.com/1392692/226171934-c8f40c73-0b3e-4512-b0a8-c774347696c4.png)
