### ISSUE TITLE
Recent activity: If one endpoint does not have a valid codeobjectid, cannot click on the other one as well

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#399]

**Comment by arik-dig** [comment]
I opened our backend project and I was able to click on the second endpoint (while the first is unbrowsable)

![image.png](https://images.zenhubusercontent.com/63fb6db2b75a9adf3c51dd6b/4f3362cd-429b-4139-8a5f-97a549f32198)

I cannot reproduce. @doppleware do you have a way to repro?
