### ISSUE TITLE
IntelliJ run instrumentation:take backend URL from settings

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#400]
Take collector backend URL from settings (make 'localhost:5050' the default)

**Comment by arik-dig** [comment]
@doppleware is this issue relates to https://github.com/digma-ai/digma-intellij-plugin/issues/306#issuecomment-1461411213 ?

**Comment by arik-dig** [comment]
suggested entry name:
**Observability Exporter URL**: http://localhost:5050
ToolTip comment: "Setup a URL for exporting the application traces"
@doppleware - is it good to go?

**Comment by doppleware** [comment]
Entry name: 
Runtime observability backend: http://localhost:5050/
Tooltip: Where should observability data be sent from the IDE? This would be the DIgma collector URL typically listening to port 5050.
