### ISSUE TITLE
No data insight not shown for endpoints 

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#419]
![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/a290ef93-101b-4bc7-bd82-ab8b5f378579)

In this case there is instrumentation (its an endpoint) so the correct empty state is 'No Data'

**Comment by arik-dig** [comment]
currently we do not have client side discovery for SpringBoot endpoints

**Comment by arik-dig** [comment]
in order to fix it, going to add client side discovery for SpringBoot, similar as we have for Micronaut and JAX-RS
