### ISSUE TITLE
when opening unsupported document (like readme) seeing the 'loading' empty state

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#433]
![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/d8e9c043-de06-4309-a0dc-bf40ba64a6dd)

**Comment by arik-dig** [comment]
@doppleware what do we want to show for unsupported objects?
as of today we show "No Insights" and "No Errors" depend on the selected card, should we keep it?

**Comment by doppleware** [comment]
Lets just show 'Unsupported File Type'

**Comment by arik-dig** [comment]
@doppleware actually its a new requirement.
I rather keep the system as it used to be - don't want to add more states at this time - since we want stable version.
I will keep the existing view of "No Insights" and "No Errors"
