### ISSUE TITLE
environment list issues after user clicks on recent activity item

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#438]
STR
See attached video
https://drive.google.com/file/d/1k2T9lgv74NMtH4dEK1EGlUI6ay-5dBM1/view?usp=share_link
please **download** the file and run it

I think that the main issues start because the 2 environment lists are not synced, please consult with @MykolaYaremchuk

**Comment by MykolaYaremchuk** [comment]
looks like combobox is not notified about the clicked env event, this issue can be related to memory leak fix
