### ISSUE TITLE
Empty state for  class view

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#464]
If the user click outside of a method and in a class we show 'no insights'.
We should either:
1. If we can find endpoints or spans in the class, show the 'No data' empty state
2. Otherwise show the No Insights empty state

**Comment by arik-dig** [comment]
@doppleware soon with the new UI, our focused object cannot be class (outside of method),
1. Do we **still** want to address this issue at all now?
2. Should we consider in the new UI to have focus on entire file (or class, or multiple classes)?

**Comment by doppleware** [comment]
Yes we'll have an option to see all assets in a specific class, so this empty state will still be important

**Comment by arik-dig** [comment]
blocked by #280 since we have client side discovery and we must have the scope of insights per method (and from that insights by class), only then we could know if there are no really insights per class
