### ISSUE TITLE
Unable to merge values from run config into Digma's injected ones

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#472]
The user should be able to specify the following env variables:

OTEL_SERVICE = x
OTEL_RESOURCE_ATTRIBUTES= x=y,p=z

When activating the 'Observability' toggle button, these values should be merged with Digma's with the user's values taking precedence.
Need to also check the VM Options equivalent

**Comment by arik-dig** [comment]
OTEL_SERVICE is single value, and cannot be merged, I guess that if already exists, Digma should not override it.
regarding OTEL_RESOURCE_ATTRIBUTES - merge sounds a must

**Comment by doppleware** [comment]
Exactly - Digma shouldn't override it if exists.

**Comment by arik-dig** [comment]
I manage to read the existing systemPropeties for Maven and regular java program, but for GradleRun, I cannot reach them - I opened a bug so we could track it:
https://youtrack.jetbrains.com/issue/IDEA-317118
