### ISSUE TITLE
Clicking on a link to a specific location should trigger refresh

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#474]
Reproduced from activity feed.
After clicking on an endpoint I was navigated to a location where it said 'no insights'
When I clicked 'refresh' manually the insights were shown.

Intended behavior: Refresh insights on navigation to a location via recent/link from insight

**Comment by arik-dig** [comment]
it should display processing insights... (pending).
unless there's a race condition and we have no environments at all.

**Comment by doppleware** [comment]
@arik-dig  Processing is only for the first insight 
If there is already an insight (duration) but I clicked from a different location because that area was marked as 'bottleneck', I do not see that insight unless I referesh.
