### ISSUE TITLE
Provide a way for the plugin to request the user to update plugin /backend

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#490]
As users will start using the platform, we cannot rely on the IDE updates because they are not aggressive enough - if you don't check you don't see that you have any plugin updates.

https://www.figma.com/file/knBV9hsfk9Au7mDQdFAFea/READY-TO-DEV?node-id=1190-177711&t=GYnCSu8lOVoEUB0g-0

related to the backend issue: https://github.com/digma-ai/digma-collector-backend/issues/808

client requirements:
should call the new API periodically every 1hr
the contract should be defined between the client and the server see the related backend issue for more details.
* should show messages for both plugin or backend updates 

behavior Requirements:
* We should have complete control of which version we want to push to users, users should not be notified of every release.
* In case both the plugin and backend need to be updated, first we'll show a notification on the backend that needs to be updated, then and only if the backend was updated we'll show the user notification on plugin updates. the update order is crucial because of the case when a new API was added to the backend in order to support new client functionality.

* We need the ability to specify the version compatibility range for different intellij platformVersions to support the following cases:

Client Platform: Intellij
1. user should get an update notification if a **specific**  plugin version available in the marketplace
2. In a case, a new platformVersion has breaking changes and we released a new plugin version for it, the previous platformVersion range should be set [X.Y.Z]-[PREVIOUS_PLUGIN_VERSION], so older platformVersion will not get notified on the newest plugin version
Client Platform: vscode:
1. user should get an update notification if a specific  plugin version available in the marketplace
2.  need to discuss with @kshmidt-digma 
Backend Version:
For now, we will continue not breaking backward compatibility with clients the  backend server version to notify should be  returned from the API

This API should be fully covered with tests otherwise in case of a bug, we won't be able to push notifications to users.

Flows:

1. **Given**:
the latest backend is 1.0.1
client  backend is 1.0.1
**When** 
new backend version releases 1.0.2 **AND**  Digma would Not like to notify clients about the new version
**Then**
user should not see any notification 
2. **Given**:
the latest backend is 1.0.1
client  backend is 1.0.1
**When** 
A new backend version was released 1.0.2 **AND**  Digma would like to notify clients about the new version
**Then**
user should see the plugin backend update notification 
3. **Given**:
the latest backend is 1.0.1
the latest plugin is 2.0.0
latest platformVersion is  3.0.0
client  backend is 1.0.1
client  plugin is 2.0.0
client platformVersion is  3.0.0
**When** 
A new backend version was released 1.0.2 **AND**
A new plugin version was released 2.0.1 **AND** 
Digma would like  to notify clients about both versions
**Then**
user should see the plugin backend update notification and only after upgrading the backend he should see the  plugin update notification
4. **Given**:
the latest plugin is 2.0.1 **AND**
latest platformVersion is  4.0.0 **AND**  
plugin 2.0.0 is only compatible with platformVersion 3.0.0 and below **AND**
the client plugin is 2.0.0 **AND**
the client  platformVersion is  3.0.0
**When** 
A new plugin version was released 2.0.2 
**Then**
user should not get a notification on the new plugin version (2.0.2)
5. **Given**:
the latest plugin is 2.0.0 **AND**
latest platformVersion is  3.0.0 **AND** 
the client plugin is 2.0.0 **AND**
the client  platformVersion is  3.0.0
**When** 
A new  platformVersion released 4.0.0 **AND**  new  plugin released 2.0.1 **AND**  
plugin 2.0.1 is only compatible with platformVersion 4.0.0 and above
**Then**
user should not get a notification on the new plugin version (2.0.2)
6. ?
7.

**Comment by arik-dig** [comment]
took a print screen from Figma:
![image.png](https://images.zenhubusercontent.com/63fb6db2b75a9adf3c51dd6b/a329fbdd-1a76-4f61-bc5a-5016daf4c901)

**Comment by arik-dig** [comment]
I managed to extract the Dark icon:

![update-product-dark.svg](https://images.zenhubusercontent.com/63fb6db2b75a9adf3c51dd6b/8e442491-4541-447a-a771-07ffcc6b3ce7)

@shaykeren , @doppleware, @shalom938, @kshmidt-digma   any ideas how to extract the lighter version of it?

**Comment by kshmidt-digma** [comment]
You can export it from Figma the same way as the dark one.

Here it is:
![Update](https://user-images.githubusercontent.com/119138536/234039776-a69234db-f7f9-48fc-ae2d-c1ba41e3e0c4.svg)

Note: as it's a SVG (text file) you can just replace the fill color with the one you need. (e.g. this one has  #002D61)

**Comment by arik-dig** [comment]
@kshmidt-digma thanks.

**Comment by arik-dig** [comment]
@doppleware , @shaykeren we have enum for DeploymentType:

```
enum class BackendDeploymentType {
    SAAS,
    DockerCompose,
    DockerExtension,
```

can you please provide the UI needed per type?
as of now, I know that for docker type, the button will open the link to our extension.
but what should we do for other types?

**Comment by arik-dig** [comment]
agreed with @shaykeren that for DockerCompose i'm going to create similar text as provided in our wizard:

![image.png](https://images.zenhubusercontent.com/63fb6db2b75a9adf3c51dd6b/fb8a7691-fa7a-4a97-8a3e-6f6b0bb1672e)

and will open in the editor a readme_update.md file

@doppleware any more comments?

**Comment by arik-dig** [comment]
I modified the text a bit so a user could know whether he's gonna update the **backend** or the **plugin**.

![image](https://user-images.githubusercontent.com/104715391/235430900-c3a90839-d34a-48f9-bc59-b3fb49f753bc.png)

here are the texts:
`Update Digma | Install latest plugin version`
`Update Digma | Install latest backend version`

@doppleware can you approve?

**Comment by arik-dig** [comment]
agreed with @shaykeren to lower to frequency check to 5 minutes, so we won't maintain different timers, for checking backend and/or plugin versions.

**Comment by doppleware** [comment]
@arik-dig text should be:
`Update Recommended | Digma analysis backend`
`Update Recommended | Digma IDE plugin`
