### ISSUE TITLE
Add annotations sometimes appears and sometimes doesn't with 'loading' showing in place of it

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#505]
See the below video:
https://drive.google.com/file/d/17zUvIbpD59_zE8bRmPgzWTm52z1qQWFe/view?usp=sharing

**Comment by asafchen-dig** [comment]
@doppleware , lets have a session and show how to reproduce it

**Comment by doppleware** [comment]
its doesn't always reproduce...

**Comment by doppleware** [comment]
From what I'm seeing in the code... It looks pretty straightforward:
![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/a77e0c02-5d99-4e9e-9972-bf24b5f4a479)

If we don't know the insight state (probably interim state) then it will show that before the no observability state.
The fix should be to change the order, this client-side sitate (no observability) show be checked before the server side insight status unknown state.

**Comment by doppleware** [comment]
However, there seems to be a mess in the refresh order - I'll show you

**Comment by doppleware** [comment]
@asafchen-dig see my fix here:
https://github.com/digma-ai/digma-intellij-plugin/pull/506/files#diff-715f2382f93fb8763f638eae38ac303f7498103688f16b62cc83e8eb672b22e0

It seems to work, can you review it?
