### ISSUE TITLE
CodeLens are not working well with DotNet project on main branch

### ISSUE THREAD

**Issue by MykolaYaremchuk** [digma-ai/digma-intellij-plugin#536]
CodeLens work great inside Java project and work strange with DotNet Sample.
Go to latest main branch (plugin version=2.0.61) and play with it (in some rear cases code lens are being displayed for .cs files but usually no CodeLens at all)

**Comment by shalom938** [comment]
@borisermakof can you please clarify the relation between this issue and 768 ?

**Comment by shalom938** [comment]
This issue describes a technical problem with code lens in Rider.
Borys is talking about that we don't have discovery for endpoints in C#, 
two different things.

I could not reproduce the original bug description.

@shaykeren  please decide what to do with this bug. I can't reproduce

**Comment by shaykeren** [comment]
cannot reprocued
