### ISSUE TITLE
connection error - doesn't look good(see screenshot)

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#558]
![image.png](https://images.zenhubusercontent.com/63ec76164ec7e010c1af91fc/f63516f1-5197-469e-bdc1-00077e7d17ef)

@doppleware  - maybe we should ask Inkod to help with this one

**Comment by doppleware** [comment]
See new UI

https://www.figma.com/file/knBV9hsfk9Au7mDQdFAFea/READY-TO-DEV?type=design&node-id=1721-234449&t=QFBrlSfPniJeqeBM-0
