### ISSUE TITLE
Embedded Jaeger should become the default if no other Jaeger was defined

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#589]
Users upgrading to the new release with Jaeger who did not define any Jaeger already should have the embedded Jaeger be the default option (mode + URL)

**Comment by arik-dig** [comment]
@doppleware I don't think we can know if user has modified the settings entries, we just know the current values of settings.
so we can check if the values were the previous defaults we'll modify them to new defaults.
makes sense?

**Comment by doppleware** [comment]
If there is no URL for Jaeger plugin should set it to the default and set embedded
