### ISSUE TITLE
Errors tab is neglected with regard to empty state messages 

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#618]
empty state messages like NoInsights, NoDataYet ,NoObservability are implemented only in the insights tab.
The errors tab still show old messages and does not handle all the statuses.

![image.png](https://images.zenhubusercontent.com/6408f831037b5b33be64bbd2/6755dddf-24d8-4dd1-9e92-e5deeabab5a2)

![image.png](https://images.zenhubusercontent.com/6408f831037b5b33be64bbd2/435608f6-2102-4fc9-996e-ed50f165c2a3)

**Comment by doppleware** [comment]
See the requested design:
https://www.figma.com/file/knBV9hsfk9Au7mDQdFAFea/READY-TO-DEV?type=design&node-id=1712%3A256736&t=68nAlnLMPmH6kpj7-1

**Comment by arik-dig** [comment]
Here's the screenshot from Figma:

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/6f8af58b-821c-4e3d-b3f1-1bdb7009da42)

@doppleware 
where does the `Here` link browses?

**Comment by arik-dig** [comment]
Roni's answer: 
1. (remove here link)
2. no need to capitalize each word
