### ISSUE TITLE
selecting environment in the tool window should select the same environment in observability window

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#620]

**Comment by shalom938** [comment]
ans also remember the selected environment from persistence in observability

**Comment by arik-dig** [comment]
@shalom938 , @shaykeren 
I think there's a regression issue since the new navigation.
the links from recent activity won't modify the environment on the side panel.

**Comment by shalom938** [comment]
I think that recent activity never had this behavior  that changing environment also changes in the side panel.
this is what this bug was opened about , that they should be synced.

**Comment by arik-dig** [comment]
yes it had, see issue #349 + PR #387 fixing it
