### ISSUE TITLE
Trigger refresh after following any link in IntelliJ Plugin

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#635]
We see the following situation given that:

method1:Endpoint1 -> method2:Span1 [bottleneck]

1. Time: 1:30 minutes, only span duration insights are calculated, 
2. We open method2 first (and see only duration has been calculated)
3. Time: 2:30 we see in the recent activity a bottleneck was found in Endpoint1
4. We click the recent activity link and see the endpoint bottleneck insight with a link to the root cause: span1
5. We click the link but view is not refreshed, we still see duration, user needs to know to refresh

Expected behavior: Similar to refreshing after clicking Recent Activity link, we should refresh when following internal link between insights

**Comment by arik-dig** [comment]
chosen approach for solve : 
whenever focus on a method, going to make a backend call for insights only for that specific method, and update the cache for its entry
