### ISSUE TITLE
Updated no connection page UI

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#663]
https://www.figma.com/file/knBV9hsfk9Au7mDQdFAFea/READY-TO-DEV?type=design&node-id=1721%3A234449&t=68nAlnLMPmH6kpj7-1

**Comment by arik-dig** [comment]
@doppleware 
it seems that in existing screen we have 3 links:
1. Refresh
2. Install
3. Setup Digma  

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/03782da1-439d-4d30-a79e-529de8566a70)

while in the new screen all those 3 are out:

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/6b25041a-b5ab-4a60-b895-61515829ada4)

is it on purpose?

**Comment by arik-dig** [comment]
roni's answer:
Just remove the capitalization anywhere except the headline, add a link to the wizard (“Rerun the Digma onboarding Wizard")
