### ISSUE TITLE
Add data about span insights for the Jaeger UI

### ISSUE THREAD

**Issue by kshmidt-digma** [digma-ai/digma-intellij-plugin#669]
To display insights in Jaeger UI for each span plugin needs to provide additional payload in message.

API changes:

1. Message names have been replaced to avoid confusion and be more accurate to the their current behaviour:
-   `GET_SPANS_WITH_RESOLVED_LOCATION` -> `GET_SPANS_DATA`
-   `SET_SPANS_WITH_RESOLVED_LOCATION` -> `SET_SPANS_DATA`

2. `SET_SPANS_DATA` message payload should be the following:
```
{
    [spanId]: {
      hasCodeLocation: boolean,
      insights: { type: string, importance: number }[],
    },
    ...   
}
```

Example:
```
{
   "2e55147853e81b6e": {
      "hasCodeLocation": true,
      "insights": [
         {
            "type":"SpanDurations",
            "importance":2
         },
         {
            "type":"SlowEndpoint",
            "importance":5
         },
         {
            "type":"SlowestSpans",
            "importance":7
         },
         {
            "type":"Errors",
            "importance":2
         }
      ]
   },
   "3a53147854e11c6a": {
      "hasCodeLocation": false,
      "insights": []
   }
}
```
Dev noted:
We should show all insights related to the span, currently in the backend we are getting only high-importance insights so this filter should be removed.

**Comment by shalom938** [comment]
@kshmidt-digma @shaykeren @doppleware 

See PR:
[add data about span insights jaeger](https://github.com/digma-ai/digma-intellij-plugin/pull/687)

questions:

1)
can there be no insights for a span?

I mean that getInsights returns empty list.
see here: 
[JaegerUIService](https://github.com/digma-ai/digma-intellij-plugin/blob/add-data-about-span-insights-jaeger-669/src/main/java/org/digma/intellij/plugin/jaegerui/JaegerUIService.java#LL313C43-L313C43)


2)
I filtered Unmapped insights from getInsights, is that ok?
see [JaegerUIService](https://github.com/digma-ai/digma-intellij-plugin/blob/add-data-about-span-insights-jaeger-669/src/main/java/org/digma/intellij/plugin/jaegerui/JaegerUIService.java#LL313C43-L313C43)

3)
can there be more then one insight with same type for a span? if not then we don't need this distinct function:
[distinctByType](https://github.com/digma-ai/digma-intellij-plugin/blob/add-data-about-span-insights-jaeger-669/src/main/java/org/digma/intellij/plugin/jaegerui/JaegerUIService.java#LL290C29-L290C29)

4)
Sometimes there are two trace buttons that want to show the same span+traceId, for example in method OwnerRepository#findPetTypes
