### ISSUE TITLE
Improve our ability to add the dependencies for manual instrumentaiton

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#670]
Currently, we are only able to suggest to add dependencies.
We want to be able to offer a link to do it for the user.

Take a look at these code examples:

https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java

https://github.com/openrewrite/rewrite/blob/main/rewrite-gradle/src/main/java/org/openrewrite/gradle/AddProperty.java

**Comment by arik-dig** [comment]
here are the UI modifications:

Link to figma:

**No observability/option 1 (autofix)**
https://www.figma.com/file/knBV9hsfk9Au7mDQdFAFea/READY-TO-DEV?type=design&node-id=624-141640&t=rnvsn44khxFGyfYQ-0

**No observability/option 2 (autofix)**
https://www.figma.com/file/knBV9hsfk9Au7mDQdFAFea/READY-TO-DEV?type=design&node-id=624-142731&t=ffD6yXRZ8I7bAQvT-0

1.
![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/6bf0742c-4591-4ad5-99f7-79f501c16103)

2. 
![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/d4885a50-807a-445b-ad6c-f33a81a4ba48)
