### ISSUE TITLE
Support instrumenting Gradle tasks

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#673]
We discussed the following workflow.

The user will create a run config for the gradle task (happens automatically when you run it)
Edit the run config and add a 'markup environment variable'. In our case 'DIGMA_OBSERVABILITY=true'

In our auto-instrumentation we look for that value and automatically instrument run configs that have it

**Comment by shalom938** [comment]
@doppleware @shaykeren 
maybe we can use [Gradle Tooling API](https://docs.gradle.org/current/userguide/third_party_integration.html#embedding)

we can query the build on project startup and keep information about tasks that are interesting for us, and when the user executes a task from the run configuration we already know what type the task is and if we want to instrument it.

This is a simple program to query for tasks with [ModelBuilder](https://docs.gradle.org/current/javadoc/org/gradle/tooling/ModelBuilder.html)

```
 ProjectConnection connection = GradleConnector.newConnector()
    .forProjectDirectory(new File("someFolder"))
    .connect();

 try {
    ModelBuilder<GradleProject> builder = connection.model(GradleProject.class);

    //configure the standard input in case your build is interactive:
    builder.setStandardInput(new ByteArrayInputStream("consume this!".getBytes()));

    //if you want to listen to the progress events:
    ProgressListener listener = null; // use your implementation
    builder.addProgressListener(listener);

    //get the model:
    GradleProject project = builder.get();

    //query the model for information:
    System.out.println("Available tasks: " + project.getTasks());
 } finally {
    connection.close();
 }

```

**Comment by doppleware** [comment]
Lets try this, we have a user waiting for a solution

**Comment by arik-dig** [comment]
@shalom938 , @doppleware I tried the Gradle Tooling API, and no luck, I could not figure out the gradle task type.
I even tried GradleRunConfiguration (IntelliJ class which represents the gradle task) and i could not figure out the task type.

Let me suggest alternatives:

### Option 1
Roni's suggestion with dedicated environment variable

### Option 2

Shalom's, using the Gradle Tooling API

### Option 3
Use the existing [OTEL environment variables standards](https://opentelemetry.io/docs/concepts/sdk-configuration/general-sdk-configuration/) so if we see the usage of one of them, by prefix, we apply our instrumentation 

### Option 4

Use dedicated gradle group name, for example "observed app". 
using the GradleRunConfiguration (by Intellij) we can lookup for the group name.
see in our petclinic app for example:
https://github.com/digma-ai/otel-sample-app-java/blob/main/build.gradle#L61

```
task runClientTester(type: JavaExec) {
    group = "Execution"
```

**Comment by arik-dig** [comment]
I'm in favor of option 3, since its straight forward and goes with OTEL standard

**Comment by doppleware** [comment]
After discussion it was decided to go with option 1

**Comment by arik-dig** [comment]
I think that combination of option 1 and 3 is the golden way.
if customer is familiar with OTEL then we're fine, and no need for extra definition.

**Comment by doppleware** [comment]
Sure sounds good. Either OTEL or our attributes

**Comment by arik-dig** [comment]
I had a discussion with Shalom and we thought about maintaining a list of tasks names that would be observed, and the user might edit the list (in the settings)
also, Shalom suggest a dynamic way of collecting the list so whenever user runs a task which is not yet in the list we will raise a pop-up (only once per task) which looks something like that:
![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/9a2c9b78-5844-4224-aecb-791071e5ae0b)

and we'll store the info about it, and futuristic calls would look at the stored list.
@doppleware what do you say?

**Comment by arik-dig** [comment]
another downside of options 1 and 3 is that a user MUST configure his RunConfig.
lets say our user configures a gradle task:
![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/b79319f8-6ebc-4999-bcc3-77a5ffe0f051)
and clicks on the green play button at the side.

we cannot access the declared environment variables there.... (unless we parse the gradle file(s) - which we think is not that trivial)

now the gradle RunConfig is being created for him
and he must edit it and add the environment varaiable there:

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/9f499127-2fa0-4ba5-aa0a-b88576b728bf)

**Comment by doppleware** [comment]
Lets discuss f2f
