### ISSUE TITLE
Show which components have live data via code lens

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#716]
If a component has live data show a   🟢 icon

Check that we refresh the lens often enough

**Comment by arik-dig** [comment]
@doppleware what would be the label of that code lense?
do we have some mock for it?

**Comment by doppleware** [comment]
Label is just the emoji.

**Comment by arik-dig** [comment]
@doppleware you wanted it to be linkable.
where does the link leads to?

**Comment by doppleware** [comment]
Open both sidepanel (Insights) and Live VIew for this resource (in recent activity)

**Comment by arik-dig** [comment]
after merging I noticed that link itself wasn't handled properly.
