### ISSUE TITLE
Add 'Code location' button to navigation panel

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#719]
![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/765befb2-d408-4e8b-a5b4-276e35da6118)

Behavior is defined:
1. If there is only one direct code location - don't show any dropdown, just navigate to the location 
2. If there is an indirect location reference (like the closest discoverable span) show the dropdown with the 'related' info

https://www.figma.com/file/knBV9hsfk9Au7mDQdFAFea/READY-TO-DEV?type=design&node-id=1-4206&t=xtHEECUY8pPYYlU3-0

**Comment by shalom938** [comment]
if we are picky about the round corners then i need to replace the component, we use hint manager and its not possible to have rounded corners with it. can replace it to a custom popup.

![Screenshot from 2023-05-24 16-50-44](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/34b159dd-3b5b-4c3c-9c02-1eea71255c97)

**Comment by shalom938** [comment]
There is one issue related to finding the span in the backend that @arik-dig can explain.
@arik-dig please elaborate on the issue we found.

**Comment by shalom938** [comment]
Outing Arik:
Design Problem / Chanllenge
Shalom and I encountered a problem when getting links from the Jaeger.
the Jaeger sends us the original span names, however we in our backend modify the span name (for all kinds of reasons) mainly for grouping,
so we end up in case where we cannot find the span in the backend.
for example:
HTTP span original name is :
GET /owners/new
post digma backend processing, span name is:
HTTP GET /owners/new
optional solutions:
A. when we get spans from Jaeger, we query our backend by ORIGINAL name (yes we have that)
  pros: name matching will work
  cons: the API will be confusing. for DB Queries we won't be able to query by.
B. modify the backend, and NOT make transformations to span names whenever possible.
    in the HTTP case there's no real need to do so - we should have kept the original name

**Comment by doppleware** [comment]
Not sure I understand how the issue is related since this is not in Jaeger?
