### ISSUE TITLE
should we refresh insights view that was opened from jaeger link?

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#772]
user is on environment X,
clicks a span link in jaeger, we open the insights view for the span.
now user changes environment to Y.
should we refresh the insights view? maybe there are no insights for the span in environment Y ? the jaeger window is still showing info for environment X.

**Comment by doppleware** [comment]
Intended behavior:
1. We should find a way to display in the Jaeger UI which environment the trace is from
2. Clicking on a link in Jaeger should also change to that environment - similar to what we do when we click on an endpoint link in the recent activity tab
3. After that the user can change to whatever environment he wants, the Jaeger is not affected by the change
