### ISSUE TITLE
Analytics update

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#793]
Let's make sure we have events for:

1. Clicking the Trace button, with the info on what insight it was
2. In the insight click button event, I know we have the button type but we need the insight type as well
3. For clicking 'Errors' or a link to ta specific 'Error'

**Comment by shaykeren** [comment]
actions


insight button click:
event: insights button-clicked
source: %insight_type%
button: %button_name%

general button click:
event: button-clicked
source: %source_name%
button: %button_name%



recent-activity trace button click:
event: button-clicked
source: recent-activity
button: show-in-jaeger


insight trace button click:
event: insights button-clicked
source: %insight_type%
button: show-in-jaeger
