### ISSUE TITLE
Did not see observability data for local environment until plugin reset

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#803]
I have just exected an API call.
I can see the information in the Docker extension, but the environment and data does not appear int he observability anel in the plugin:

![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/b12a979f-2eb2-491b-a4de-6200e471b9eb) 

![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/d03e46bc-bc32-4a23-ace0-ed453db017b6)

Please note that in the Docker extension, I see two environments, this may the issue?

![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/8295c328-d94a-4730-a24f-e59255f6f8e8)

After restarting the plugin, the data suddenly appeared:

![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/4466817e-13e7-4669-bc60-c0a06a4d7469)

**Comment by asafchen-dig** [comment]
I can't reproduce it
@doppleware lets' have a session

**Comment by doppleware** [comment]
Probably related to the recent activity refresh issue, closing
