### ISSUE TITLE
Seeing 'no environments' and unable to see insights

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#835]
![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/ce25af9e-e21e-40e0-ac33-b9a9cb23674a)

Please see the above screenshot. 
The environment exists but I am unable to see the data in Digma.

I can see data in the recent activity panel.

[https://app.zenhub.com/files/472408329/6d9bcfff-ee47-4b8b-8778-80ce7b117958/download](https://app.zenhub.com/files/472408329/6d9bcfff-ee47-4b8b-8778-80ce7b117958/download)

**Comment by asafchen-dig** [comment]
Couldn't not reproduce
After talking with @doppleware , I'm leaving it until the next occurrence
