### ISSUE TITLE
Insights panel reverts to 'Processing Insights' even if few moments ago there insights already 

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#837]
I'm not sure how to reproduce it, see logs and video
https://drive.google.com/file/d/1XqVOKbFD862bezfe-s3dUnyVJfKTEN25/view?usp=sharing
https://drive.google.com/file/d/1jnsHlHAcjKiTJfVkS3Ory0JT_nINE-0u/view?usp=sharing

volumes:
https://drive.google.com/file/d/1hXQ-pY5BPIJkhbG7rh4XGjcOXZXSVJ82/view?usp=sharing

**Comment by borisermakof** [comment]
fixed with reverting breaking contract changes
