### ISSUE TITLE
Send empty array instead of null when there is no assets to show

### ISSUE THREAD

**Issue by kshmidt-digma** [digma-ai/digma-intellij-plugin#847]
Plugin sends `null` instead of empty array `[]` in the `ASSETS/SET_DATA` message when there are no assets to show

Scenario to reproduce:
- Install Digma backend from scratch (with no data) or clear the volumes
- Open Assets View
- See error message in Dev Tools

<img width="757" alt="image" src="https://github.com/digma-ai/digma-intellij-plugin/assets/119138536/787d4233-0e56-48a5-8350-e6db30673f2c">

**Comment by shalom938** [comment]
but payload is an object not array
do you want this?
payload: {}

**Comment by kshmidt-digma** [comment]
You're right, it's my fault. `null` is okay for this case. I'll handle it on UI side.
