### ISSUE TITLE
'Related code object' navigation should not disable the code navigation button

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#857]
STR:
Go to SQL query span in the side panel
Select the 'target' icon, see 'related code objects appear'
After the popup closes you can't open it again to see the related code objects because it has become disabled.
See video

https://images.zenhubusercontent.com/472408329/a3628e30-0af3-4d0c-8728-ba0dee0e9fc2/screen_recording_2023_06_24_at_11_27_05_am.mov

**Comment by asafchen-dig** [comment]
Regression bug because of https://github.com/digma-ai/digma-intellij-plugin/pull/844
