### ISSUE TITLE
no automatic refresh - plugin environments list

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#888]
@shaykeren commented on [Thu Jun 29 2023](https://github.com/digma-ai/digma-vscode-plugin/issues/286)

https://digmatechnicalteam.slack.com/files/U02KWBA801W/F05EQDWV18A/image.png

the issue resolved when user clicks on the recent activity links
expected result: we should automatically refresh the main environment list

**Comment by shalom938** [comment]
@shaykeren I can't reproduce

**Comment by shaykeren** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Digma-Team-629081e5a37b4b0015ac6813/issues/digma-ai/digma-intellij-plugin/888?planning-poker) with Zenhub @arik-dig @asafchen-dig @borisermakof @kshmidt-digma @shalom938
