### ISSUE TITLE
wrong span display name

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#891]
### Endpoint Duration Slowdown Panel

![image.png](https://images.zenhubusercontent.com/63ec76164ec7e010c1af91fc/9309765a-90e3-41c2-94cb-8608d6400f52)

### Errors Panel
 
<img width="553" alt="image" src="https://github.com/digma-ai/digma-intellij-plugin/assets/1392692/1014b95d-a94b-45a7-90ad-7d5be05b7a68">

**Comment by arik-dig** [comment]
In **errors display** we don't have the `SpanInfo` (display name) - the change might be more complex.
btw its a conditional code:

https://github.com/digma-ai/digma-intellij-plugin/blob/44a6cadda2d70797c151a1950540d96e316b97ea/src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/ErrorsPanel.kt#L29

and the sourceCodeObjectId might be either span or method.
we see the hash value, only when its a span

**Comment by arik-dig** [comment]
reopened since ERRORs not addressed yet

**Comment by arik-dig** [comment]
reg errors view:
seems to be related to backend issue https://github.com/digma-ai/digma-collector-backend/issues/990 maybe it was not fully fixed

**Comment by arik-dig** [comment]
still seeing the error in Meloona

`Npgsql.NpgsqlException From DDD219A803107C7F107FDC1B41D944`

and it happens for query/span:

`
INSERT INTO spans(account_id, environment, instrumentation_library, span, code_object_id, span_role, span_classification, kind, original_name, span_code_object_id, display_name, latest_span_timestamp) VALUES (@AccountId_0, @Environment_0, @InstrumentationLibrary_0, @Span_0, @CodeObjectId_0, @SpanRole_0, @SpanClassification_0, @Kind_0, @SpanOriginalName_0, @SpanCodeObjectId_0, @DisplayName_0, @LatestSpanTimestamp_0), (@AccountId_1, @Environment_1, @InstrumentationLibrary_1, @Span_1, @CodeObjectId_1, @SpanRole_1, @SpanClassification_1, @Kind_1, @SpanOriginalName_1, @SpanCodeObjectId_1, @DisplayName_1, @LatestSpanTimestamp_1), (@AccountId_2, @Environment_2, @InstrumentationLibrary_2, @Span_2, @CodeObjectId_2, @SpanRole_2, @SpanClassification_2, @Kind_2, @SpanOriginalName_2, @SpanCodeObjectId_2, @DisplayName_2, @LatestSpanTimestamp_2), (@AccountId_3, @Environment_3, @InstrumentationLibrary_3, @Span_3, @CodeObjectId_3, @SpanRole_3, @SpanClassification_3, @Kind_3, @SpanOriginalName_3, @SpanCodeObjectId_3, @DisplayName_3, @LatestSpanTimestamp_3), (@AccountId_4, @Environment_4, @InstrumentationLibrary_4, @Span_4, @CodeObjectId_4, @SpanRole_4, @SpanClassification_4, @Kind_4, @SpanOriginalName_4, @SpanCodeObjectId_4, @DisplayName_4, @LatestSpanTimestamp_4), (@AccountId_5, @Environment_5, @InstrumentationLibrary_5, @Span_5, @CodeObjectId_5, @SpanRole_5, @SpanClassification_5, @Kind_5, @SpanOriginalName_5, @SpanCodeObjectId_5, @DisplayName_5, @LatestSpanTimestamp_5), (@AccountId_6, @Environment_6, @InstrumentationLibrary_6, @Span_6, @CodeObjectId_6, @SpanRole_6, @SpanClassification_6, @Kind_6, @SpanOriginalName_6, @SpanCodeObjectId_6, @DisplayName_6, @LatestSpanTimestamp_6) ON CONFLICT (account_id, environment, instrumentation_library, span) DO UPDATE SET code_object_id = excluded.code_object_id, span_role = excluded.span_role, span_classification = excluded.span_classification, kind = excluded.kind, original_name = excluded.original_name, span_code_object_id = excluded.span_code_object_id, display_name = excluded.display_name, latest_span_timestamp = excluded.latest_span_timestamp
`

**Comment by arik-dig** [comment]
the issue with errors is relevant to dotnet only, and it happened due to issue https://github.com/digma-ai/digma-collector-backend/issues/990- where we store span code object id, instead of method code object id.
once we clean Meloona, we should not see it anymore.

its also related to https://github.com/digma-ai/digma-collector-backend/issues/996 - where we do not parse well some stack traces in dotnet

**Comment by arik-dig** [comment]
**Meloona** been cleaned up
https://github.com/digma-ai/digma-collector-backend/issues/990#issuecomment-1685283203

closing the issue
