### ISSUE TITLE
Bug/Quarkus - RunConfig won't take place for Intellij IDEA Ultimate 

### ISSUE THREAD

**Issue by arik-dig** [digma-ai/digma-intellij-plugin#970]
it works for Intellij IDEA Community but somehow not for Ultimate

**Comment by arik-dig** [comment]
seems like when running quarkus (of Quarkus ConfigType)


![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/a7aabb03-2918-469c-9934-17c335d0ae14)

it seems like it runs class `KotlinRunConfiguration` and we're not familiar with it

**Comment by arik-dig** [comment]
seems like Ultimate has builtin plugin for quarkus

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/e565c817-651a-420b-b610-6acb850b39f9)

once clicking it seeing the RunConfigs

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/093f77ab-8758-4cef-8e7b-7b1f5f5901c7)

note there are 2 quarkus sections - 
1) the shorter one is via StandAlone Quarkus plugin name Quarkus Tools ([link](https://plugins.jetbrains.com/plugin/13234-quarkus-tools))
2) the built-in Plugin of Ultimate

**Comment by arik-dig** [comment]
the Standalone plugin works and tested since its just a wrapper to `MavenRunConfiguration` which appends task named `quarkus:dev`

now going to investigate what happens with the built-in plugin

**Comment by arik-dig** [comment]
I tried to debug, and it seems that when calling `isApplicableFor` we manage to return true, since the configuration class is `QsMavenRunConfiguration` (not familiar with) - but it behaves exactly as `MavenRunConfiguration` (the common impl) however the `updateJavaParameters` is not being called - not sure why, so its either Intellij Ultimate or the Quarkus built-in Plugin.
need further investigation - but it looks like a platform bug

**Comment by arik-dig** [comment]
I opened a bug in intellij
https://youtrack.jetbrains.com/issue/IDEA-325713
waiting for feedback

**Comment by doppleware** [comment]
the bug was fixed we need to retest in the latest build

**Comment by arik-dig** [comment]
bug was fixed:
https://youtrack.jetbrains.com/issue/IDEA-325713/Quarkus-method-updateJavaParameters-in-RunConfigurationExtension-not-called-when-running-Quarkus-run-configuration#focus=Comments-27-7948305.0-0
