### ISSUE TITLE
local agent installation failure

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#978]
In case of failure while installing local agent the following screen is shown:
![image.png](https://images.zenhubusercontent.com/63ec76164ec7e010c1af91fc/4a970d7e-30c3-49aa-856e-dea82f2f0c2d)

Generic message should be displayed : "could not install engine" and not the exit code
in case of installation failure, we should perform uninstall, and the containers should be removed

**Comment by shalom938** [comment]
@shaykeren 
I f you install successfully once, then stop , and then try to start and it fails, remove the containers ?
